#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vouchar_Program
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TEST")]
	public partial class LinqVoucherDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTblHrEmp(TblHrEmp instance);
    partial void UpdateTblHrEmp(TblHrEmp instance);
    partial void DeleteTblHrEmp(TblHrEmp instance);
    partial void InsertSTblVoucher(STblVoucher instance);
    partial void UpdateSTblVoucher(STblVoucher instance);
    partial void DeleteSTblVoucher(STblVoucher instance);
    #endregion
		
		public LinqVoucherDataContext() : 
				base(global::Vouchar_Program.Properties.Settings.Default.TESTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqVoucherDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqVoucherDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqVoucherDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqVoucherDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TblHrEmp> TblHrEmps
		{
			get
			{
				return this.GetTable<TblHrEmp>();
			}
		}
		
		public System.Data.Linq.Table<View_Emp> View_Emps
		{
			get
			{
				return this.GetTable<View_Emp>();
			}
		}
		
		public System.Data.Linq.Table<STblVoucher> STblVouchers
		{
			get
			{
				return this.GetTable<STblVoucher>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblHrEmp")]
	public partial class TblHrEmp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EmpNo;
		
		private string _FullNameArab;
		
		private string _FirstNameArab;
		
		private string _SecondNameArab;
		
		private string _ThirdNameArab;
		
		private string _LastNameArab;
		
		private string _FullNameEng;
		
		private string _FirstNameEng;
		
		private string _SecondNameEng;
		
		private string _ThirdNameEng;
		
		private string _LastNameEng;
		
		private int _sponsorNo;
		
		private System.Nullable<int> _DepartmentNo;
		
		private System.Nullable<int> _CategoryVisa;
		
		private System.Nullable<int> _CategoryQualification;
		
		private System.Nullable<int> _Qualification;
		
		private System.Nullable<int> _Nationality;
		
		private System.Nullable<int> _Religion;
		
		private System.Nullable<System.DateTime> _BirhtDateG;
		
		private System.Nullable<System.DateTime> _BirhtDateH;
		
		private string _BirthPlace;
		
		private System.Nullable<int> _BankNo;
		
		private string _AccountBankNo;
		
		private string _PhoneNum;
		
		private string _EmailAddress;
		
		private System.Nullable<int> _Gender;
		
		private System.Nullable<int> _SocialStatus;
		
		private System.Nullable<int> _EmpStatus;
		
		private System.Nullable<int> _EmployeeLocation;
		
		private System.Nullable<int> _PreviousExperince;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _DirectManager;
		
		private string _AlternativeEmp;
		
		private System.Nullable<int> _FamilyStatus;
		
		private System.Nullable<int> _NumberOfChildern;
		
		private System.Nullable<int> _CampNO;
		
		private System.Nullable<int> _RoomNo;
		
		private string _CurrentAddress;
		
		private string _PermanentAddress;
		
		private string _Notes;
		
		private System.Nullable<int> _VisaDetailID;
		
		private string _BorderNo;
		
		private System.Nullable<System.DateTime> _EntryDateH;
		
		private System.Nullable<System.DateTime> _EntryDateG;
		
		private System.Nullable<int> _EntryPlace;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private string _PassportNo;
		
		private System.Nullable<System.DateTime> _PassportIssueDateG;
		
		private System.Nullable<System.DateTime> _PassportIssueDateH;
		
		private System.Nullable<System.DateTime> _PassportExpiryDateG;
		
		private System.Nullable<System.DateTime> _PassportExpiryDateH;
		
		private System.Nullable<int> _PassportIssuePlace;
		
		private string _IqamaNo;
		
		private System.Nullable<System.DateTime> _IqamaIssueDateH;
		
		private System.Nullable<System.DateTime> _IqamaIssueDateG;
		
		private System.Nullable<System.DateTime> _IqamaExpiryDateH;
		
		private System.Nullable<System.DateTime> _IqamaExpiryDateG;
		
		private System.Nullable<int> _IqamaIssuePlace;
		
		private string _WPNo;
		
		private System.Nullable<System.DateTime> _WPIssueDateH;
		
		private System.Nullable<System.DateTime> _WPIssueDateG;
		
		private System.Nullable<System.DateTime> _WPExpiryDateH;
		
		private System.Nullable<System.DateTime> _WPExpiryDateG;
		
		private System.Nullable<int> _WPPlace;
		
		private string _DriveLicenseNo;
		
		private System.Nullable<System.DateTime> _DLIssueDateH;
		
		private System.Nullable<System.DateTime> _DLIssueDateG;
		
		private System.Nullable<System.DateTime> _DLExpiryDateH;
		
		private System.Nullable<System.DateTime> _DLExpiryDateG;
		
		private System.Nullable<int> _DLPlace;
		
		private System.Nullable<int> _DLCalss;
		
		private string _GosiNo;
		
		private System.Nullable<System.DateTime> _GosiIssueDateG;
		
		private System.Nullable<System.DateTime> _GosiIssueDateH;
		
		private System.Nullable<System.DateTime> _GosiExpiryDateG;
		
		private System.Nullable<System.DateTime> _GosiExpiryDateH;
		
		private System.Nullable<int> _GosiPlace;
		
		private System.Nullable<decimal> _GosiAmount;
		
		private System.Nullable<int> _InjuryCount;
		
		private System.Nullable<int> _BirthPlaceCity;
		
		private string _ImagePath;
		
		private string _WorkOrderID;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<System.DateTime> _DateOfArchive;
		
		private System.Nullable<int> _ArchiveUserID;
		
		private System.Nullable<bool> _Hired;
		
		private System.Nullable<int> _Staff;
		
		private string _InsurancePolicyNO;
		
		private string _InsuranceReferenceNo;
		
		private string _InsuranceMembershipNO;
		
		private System.Nullable<int> _InsuranceClass;
		
		private System.Nullable<System.DateTime> _InsuranceJoiningDate;
		
		private System.Nullable<System.DateTime> _InsuranceDisJoiningDate;
		
		private string _InsuranceNotes;
		
		private System.Nullable<int> _CurrentCategory;
		
		private string _DepartmentID;
		
		private string _BloodGroup;
		
		private System.Nullable<System.DateTime> _ExpectedVacationDate;
		
		private System.Nullable<System.DateTime> _ExpectedVacationDateH;
		
		private System.Nullable<int> _SponsorNoOld;
		
		private System.Data.Linq.Binary _ImageID;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
		private System.Nullable<System.DateTime> _StatusDate;
		
		private System.Nullable<int> _BankNo2;
		
		private string _AccountBankNo2;
		
		private System.Nullable<System.DateTime> _UpdatedDateBank2;
		
		private System.Nullable<int> _BankNo3;
		
		private string _AccountBankNo3;
		
		private System.Nullable<System.DateTime> _UpdatedDateBank3;
		
		private System.Nullable<System.DateTime> _ESBDate;
		
		private string _Guaranteed;
		
		private System.Nullable<System.DateTime> _DateOfGuarantee;
		
		private string _PurposeOfGuarantee;
		
		private System.Nullable<decimal> _AmountOfGuarantee;
		
		private string _IBANBank1;
		
		private string _IBANBank2;
		
		private string _IBANBank3;
		
		private System.Nullable<System.DateTime> _ResidentIdentityExpiryDateH;
		
		private System.Nullable<System.DateTime> _ResidentIdentityExpiryDateG;
		
		private string _VoucherNo;
		
		private System.Nullable<System.DateTime> _ExpectedReturnDateOfGuaranteed;
		
		private System.Nullable<System.DateTime> _ActualReturnDateOfGuaranteed;
		
		private string _ActionTaken;
		
		private System.Nullable<System.DateTime> _VisaExpiryDateOfGuaranteed;
		
		private System.Nullable<decimal> _WorkPermitCost;
		
		private string _WorkPermitNote;
		
		private EntitySet<STblVoucher> _STblVouchers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnFullNameArabChanging(string value);
    partial void OnFullNameArabChanged();
    partial void OnFirstNameArabChanging(string value);
    partial void OnFirstNameArabChanged();
    partial void OnSecondNameArabChanging(string value);
    partial void OnSecondNameArabChanged();
    partial void OnThirdNameArabChanging(string value);
    partial void OnThirdNameArabChanged();
    partial void OnLastNameArabChanging(string value);
    partial void OnLastNameArabChanged();
    partial void OnFullNameEngChanging(string value);
    partial void OnFullNameEngChanged();
    partial void OnFirstNameEngChanging(string value);
    partial void OnFirstNameEngChanged();
    partial void OnSecondNameEngChanging(string value);
    partial void OnSecondNameEngChanged();
    partial void OnThirdNameEngChanging(string value);
    partial void OnThirdNameEngChanged();
    partial void OnLastNameEngChanging(string value);
    partial void OnLastNameEngChanged();
    partial void OnsponsorNoChanging(int value);
    partial void OnsponsorNoChanged();
    partial void OnDepartmentNoChanging(System.Nullable<int> value);
    partial void OnDepartmentNoChanged();
    partial void OnCategoryVisaChanging(System.Nullable<int> value);
    partial void OnCategoryVisaChanged();
    partial void OnCategoryQualificationChanging(System.Nullable<int> value);
    partial void OnCategoryQualificationChanged();
    partial void OnQualificationChanging(System.Nullable<int> value);
    partial void OnQualificationChanged();
    partial void OnNationalityChanging(System.Nullable<int> value);
    partial void OnNationalityChanged();
    partial void OnReligionChanging(System.Nullable<int> value);
    partial void OnReligionChanged();
    partial void OnBirhtDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnBirhtDateGChanged();
    partial void OnBirhtDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnBirhtDateHChanged();
    partial void OnBirthPlaceChanging(string value);
    partial void OnBirthPlaceChanged();
    partial void OnBankNoChanging(System.Nullable<int> value);
    partial void OnBankNoChanged();
    partial void OnAccountBankNoChanging(string value);
    partial void OnAccountBankNoChanged();
    partial void OnPhoneNumChanging(string value);
    partial void OnPhoneNumChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnGenderChanging(System.Nullable<int> value);
    partial void OnGenderChanged();
    partial void OnSocialStatusChanging(System.Nullable<int> value);
    partial void OnSocialStatusChanged();
    partial void OnEmpStatusChanging(System.Nullable<int> value);
    partial void OnEmpStatusChanged();
    partial void OnEmployeeLocationChanging(System.Nullable<int> value);
    partial void OnEmployeeLocationChanged();
    partial void OnPreviousExperinceChanging(System.Nullable<int> value);
    partial void OnPreviousExperinceChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OnDirectManagerChanging(string value);
    partial void OnDirectManagerChanged();
    partial void OnAlternativeEmpChanging(string value);
    partial void OnAlternativeEmpChanged();
    partial void OnFamilyStatusChanging(System.Nullable<int> value);
    partial void OnFamilyStatusChanged();
    partial void OnNumberOfChildernChanging(System.Nullable<int> value);
    partial void OnNumberOfChildernChanged();
    partial void OnCampNOChanging(System.Nullable<int> value);
    partial void OnCampNOChanged();
    partial void OnRoomNoChanging(System.Nullable<int> value);
    partial void OnRoomNoChanged();
    partial void OnCurrentAddressChanging(string value);
    partial void OnCurrentAddressChanged();
    partial void OnPermanentAddressChanging(string value);
    partial void OnPermanentAddressChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnVisaDetailIDChanging(System.Nullable<int> value);
    partial void OnVisaDetailIDChanged();
    partial void OnBorderNoChanging(string value);
    partial void OnBorderNoChanged();
    partial void OnEntryDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryDateHChanged();
    partial void OnEntryDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryDateGChanged();
    partial void OnEntryPlaceChanging(System.Nullable<int> value);
    partial void OnEntryPlaceChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnPassportNoChanging(string value);
    partial void OnPassportNoChanged();
    partial void OnPassportIssueDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnPassportIssueDateGChanged();
    partial void OnPassportIssueDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnPassportIssueDateHChanged();
    partial void OnPassportExpiryDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnPassportExpiryDateGChanged();
    partial void OnPassportExpiryDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnPassportExpiryDateHChanged();
    partial void OnPassportIssuePlaceChanging(System.Nullable<int> value);
    partial void OnPassportIssuePlaceChanged();
    partial void OnIqamaNoChanging(string value);
    partial void OnIqamaNoChanged();
    partial void OnIqamaIssueDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnIqamaIssueDateHChanged();
    partial void OnIqamaIssueDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnIqamaIssueDateGChanged();
    partial void OnIqamaExpiryDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnIqamaExpiryDateHChanged();
    partial void OnIqamaExpiryDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnIqamaExpiryDateGChanged();
    partial void OnIqamaIssuePlaceChanging(System.Nullable<int> value);
    partial void OnIqamaIssuePlaceChanged();
    partial void OnWPNoChanging(string value);
    partial void OnWPNoChanged();
    partial void OnWPIssueDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnWPIssueDateHChanged();
    partial void OnWPIssueDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnWPIssueDateGChanged();
    partial void OnWPExpiryDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnWPExpiryDateHChanged();
    partial void OnWPExpiryDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnWPExpiryDateGChanged();
    partial void OnWPPlaceChanging(System.Nullable<int> value);
    partial void OnWPPlaceChanged();
    partial void OnDriveLicenseNoChanging(string value);
    partial void OnDriveLicenseNoChanged();
    partial void OnDLIssueDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnDLIssueDateHChanged();
    partial void OnDLIssueDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnDLIssueDateGChanged();
    partial void OnDLExpiryDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnDLExpiryDateHChanged();
    partial void OnDLExpiryDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnDLExpiryDateGChanged();
    partial void OnDLPlaceChanging(System.Nullable<int> value);
    partial void OnDLPlaceChanged();
    partial void OnDLCalssChanging(System.Nullable<int> value);
    partial void OnDLCalssChanged();
    partial void OnGosiNoChanging(string value);
    partial void OnGosiNoChanged();
    partial void OnGosiIssueDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnGosiIssueDateGChanged();
    partial void OnGosiIssueDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnGosiIssueDateHChanged();
    partial void OnGosiExpiryDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnGosiExpiryDateGChanged();
    partial void OnGosiExpiryDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnGosiExpiryDateHChanged();
    partial void OnGosiPlaceChanging(System.Nullable<int> value);
    partial void OnGosiPlaceChanged();
    partial void OnGosiAmountChanging(System.Nullable<decimal> value);
    partial void OnGosiAmountChanged();
    partial void OnInjuryCountChanging(System.Nullable<int> value);
    partial void OnInjuryCountChanged();
    partial void OnBirthPlaceCityChanging(System.Nullable<int> value);
    partial void OnBirthPlaceCityChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    partial void OnWorkOrderIDChanging(string value);
    partial void OnWorkOrderIDChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnDateOfArchiveChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfArchiveChanged();
    partial void OnArchiveUserIDChanging(System.Nullable<int> value);
    partial void OnArchiveUserIDChanged();
    partial void OnHiredChanging(System.Nullable<bool> value);
    partial void OnHiredChanged();
    partial void OnStaffChanging(System.Nullable<int> value);
    partial void OnStaffChanged();
    partial void OnInsurancePolicyNOChanging(string value);
    partial void OnInsurancePolicyNOChanged();
    partial void OnInsuranceReferenceNoChanging(string value);
    partial void OnInsuranceReferenceNoChanged();
    partial void OnInsuranceMembershipNOChanging(string value);
    partial void OnInsuranceMembershipNOChanged();
    partial void OnInsuranceClassChanging(System.Nullable<int> value);
    partial void OnInsuranceClassChanged();
    partial void OnInsuranceJoiningDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInsuranceJoiningDateChanged();
    partial void OnInsuranceDisJoiningDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInsuranceDisJoiningDateChanged();
    partial void OnInsuranceNotesChanging(string value);
    partial void OnInsuranceNotesChanged();
    partial void OnCurrentCategoryChanging(System.Nullable<int> value);
    partial void OnCurrentCategoryChanged();
    partial void OnDepartmentIDChanging(string value);
    partial void OnDepartmentIDChanged();
    partial void OnBloodGroupChanging(string value);
    partial void OnBloodGroupChanged();
    partial void OnExpectedVacationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpectedVacationDateChanged();
    partial void OnExpectedVacationDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnExpectedVacationDateHChanged();
    partial void OnSponsorNoOldChanging(System.Nullable<int> value);
    partial void OnSponsorNoOldChanged();
    partial void OnImageIDChanging(System.Data.Linq.Binary value);
    partial void OnImageIDChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    partial void OnStatusDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStatusDateChanged();
    partial void OnBankNo2Changing(System.Nullable<int> value);
    partial void OnBankNo2Changed();
    partial void OnAccountBankNo2Changing(string value);
    partial void OnAccountBankNo2Changed();
    partial void OnUpdatedDateBank2Changing(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateBank2Changed();
    partial void OnBankNo3Changing(System.Nullable<int> value);
    partial void OnBankNo3Changed();
    partial void OnAccountBankNo3Changing(string value);
    partial void OnAccountBankNo3Changed();
    partial void OnUpdatedDateBank3Changing(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateBank3Changed();
    partial void OnESBDateChanging(System.Nullable<System.DateTime> value);
    partial void OnESBDateChanged();
    partial void OnGuaranteedChanging(string value);
    partial void OnGuaranteedChanged();
    partial void OnDateOfGuaranteeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfGuaranteeChanged();
    partial void OnPurposeOfGuaranteeChanging(string value);
    partial void OnPurposeOfGuaranteeChanged();
    partial void OnAmountOfGuaranteeChanging(System.Nullable<decimal> value);
    partial void OnAmountOfGuaranteeChanged();
    partial void OnIBANBank1Changing(string value);
    partial void OnIBANBank1Changed();
    partial void OnIBANBank2Changing(string value);
    partial void OnIBANBank2Changed();
    partial void OnIBANBank3Changing(string value);
    partial void OnIBANBank3Changed();
    partial void OnResidentIdentityExpiryDateHChanging(System.Nullable<System.DateTime> value);
    partial void OnResidentIdentityExpiryDateHChanged();
    partial void OnResidentIdentityExpiryDateGChanging(System.Nullable<System.DateTime> value);
    partial void OnResidentIdentityExpiryDateGChanged();
    partial void OnVoucherNoChanging(string value);
    partial void OnVoucherNoChanged();
    partial void OnExpectedReturnDateOfGuaranteedChanging(System.Nullable<System.DateTime> value);
    partial void OnExpectedReturnDateOfGuaranteedChanged();
    partial void OnActualReturnDateOfGuaranteedChanging(System.Nullable<System.DateTime> value);
    partial void OnActualReturnDateOfGuaranteedChanged();
    partial void OnActionTakenChanging(string value);
    partial void OnActionTakenChanged();
    partial void OnVisaExpiryDateOfGuaranteedChanging(System.Nullable<System.DateTime> value);
    partial void OnVisaExpiryDateOfGuaranteedChanged();
    partial void OnWorkPermitCostChanging(System.Nullable<decimal> value);
    partial void OnWorkPermitCostChanged();
    partial void OnWorkPermitNoteChanging(string value);
    partial void OnWorkPermitNoteChanged();
    #endregion
		
		public TblHrEmp()
		{
			this._STblVouchers = new EntitySet<STblVoucher>(new Action<STblVoucher>(this.attach_STblVouchers), new Action<STblVoucher>(this.detach_STblVouchers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameArab", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FullNameArab
		{
			get
			{
				return this._FullNameArab;
			}
			set
			{
				if ((this._FullNameArab != value))
				{
					this.OnFullNameArabChanging(value);
					this.SendPropertyChanging();
					this._FullNameArab = value;
					this.SendPropertyChanged("FullNameArab");
					this.OnFullNameArabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstNameArab", DbType="NVarChar(50)")]
		public string FirstNameArab
		{
			get
			{
				return this._FirstNameArab;
			}
			set
			{
				if ((this._FirstNameArab != value))
				{
					this.OnFirstNameArabChanging(value);
					this.SendPropertyChanging();
					this._FirstNameArab = value;
					this.SendPropertyChanged("FirstNameArab");
					this.OnFirstNameArabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondNameArab", DbType="NVarChar(50)")]
		public string SecondNameArab
		{
			get
			{
				return this._SecondNameArab;
			}
			set
			{
				if ((this._SecondNameArab != value))
				{
					this.OnSecondNameArabChanging(value);
					this.SendPropertyChanging();
					this._SecondNameArab = value;
					this.SendPropertyChanged("SecondNameArab");
					this.OnSecondNameArabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdNameArab", DbType="NVarChar(50)")]
		public string ThirdNameArab
		{
			get
			{
				return this._ThirdNameArab;
			}
			set
			{
				if ((this._ThirdNameArab != value))
				{
					this.OnThirdNameArabChanging(value);
					this.SendPropertyChanging();
					this._ThirdNameArab = value;
					this.SendPropertyChanged("ThirdNameArab");
					this.OnThirdNameArabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNameArab", DbType="NVarChar(50)")]
		public string LastNameArab
		{
			get
			{
				return this._LastNameArab;
			}
			set
			{
				if ((this._LastNameArab != value))
				{
					this.OnLastNameArabChanging(value);
					this.SendPropertyChanging();
					this._LastNameArab = value;
					this.SendPropertyChanged("LastNameArab");
					this.OnLastNameArabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FullNameEng
		{
			get
			{
				return this._FullNameEng;
			}
			set
			{
				if ((this._FullNameEng != value))
				{
					this.OnFullNameEngChanging(value);
					this.SendPropertyChanging();
					this._FullNameEng = value;
					this.SendPropertyChanged("FullNameEng");
					this.OnFullNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstNameEng", DbType="NVarChar(50)")]
		public string FirstNameEng
		{
			get
			{
				return this._FirstNameEng;
			}
			set
			{
				if ((this._FirstNameEng != value))
				{
					this.OnFirstNameEngChanging(value);
					this.SendPropertyChanging();
					this._FirstNameEng = value;
					this.SendPropertyChanged("FirstNameEng");
					this.OnFirstNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondNameEng", DbType="NVarChar(50)")]
		public string SecondNameEng
		{
			get
			{
				return this._SecondNameEng;
			}
			set
			{
				if ((this._SecondNameEng != value))
				{
					this.OnSecondNameEngChanging(value);
					this.SendPropertyChanging();
					this._SecondNameEng = value;
					this.SendPropertyChanged("SecondNameEng");
					this.OnSecondNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdNameEng", DbType="NVarChar(50)")]
		public string ThirdNameEng
		{
			get
			{
				return this._ThirdNameEng;
			}
			set
			{
				if ((this._ThirdNameEng != value))
				{
					this.OnThirdNameEngChanging(value);
					this.SendPropertyChanging();
					this._ThirdNameEng = value;
					this.SendPropertyChanged("ThirdNameEng");
					this.OnThirdNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNameEng", DbType="NVarChar(50)")]
		public string LastNameEng
		{
			get
			{
				return this._LastNameEng;
			}
			set
			{
				if ((this._LastNameEng != value))
				{
					this.OnLastNameEngChanging(value);
					this.SendPropertyChanging();
					this._LastNameEng = value;
					this.SendPropertyChanged("LastNameEng");
					this.OnLastNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sponsorNo", DbType="Int NOT NULL")]
		public int sponsorNo
		{
			get
			{
				return this._sponsorNo;
			}
			set
			{
				if ((this._sponsorNo != value))
				{
					this.OnsponsorNoChanging(value);
					this.SendPropertyChanging();
					this._sponsorNo = value;
					this.SendPropertyChanged("sponsorNo");
					this.OnsponsorNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentNo", DbType="Int")]
		public System.Nullable<int> DepartmentNo
		{
			get
			{
				return this._DepartmentNo;
			}
			set
			{
				if ((this._DepartmentNo != value))
				{
					this.OnDepartmentNoChanging(value);
					this.SendPropertyChanging();
					this._DepartmentNo = value;
					this.SendPropertyChanged("DepartmentNo");
					this.OnDepartmentNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryVisa", DbType="Int")]
		public System.Nullable<int> CategoryVisa
		{
			get
			{
				return this._CategoryVisa;
			}
			set
			{
				if ((this._CategoryVisa != value))
				{
					this.OnCategoryVisaChanging(value);
					this.SendPropertyChanging();
					this._CategoryVisa = value;
					this.SendPropertyChanged("CategoryVisa");
					this.OnCategoryVisaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryQualification", DbType="Int")]
		public System.Nullable<int> CategoryQualification
		{
			get
			{
				return this._CategoryQualification;
			}
			set
			{
				if ((this._CategoryQualification != value))
				{
					this.OnCategoryQualificationChanging(value);
					this.SendPropertyChanging();
					this._CategoryQualification = value;
					this.SendPropertyChanged("CategoryQualification");
					this.OnCategoryQualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qualification", DbType="Int")]
		public System.Nullable<int> Qualification
		{
			get
			{
				return this._Qualification;
			}
			set
			{
				if ((this._Qualification != value))
				{
					this.OnQualificationChanging(value);
					this.SendPropertyChanging();
					this._Qualification = value;
					this.SendPropertyChanged("Qualification");
					this.OnQualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="Int")]
		public System.Nullable<int> Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="Int")]
		public System.Nullable<int> Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this.OnReligionChanging(value);
					this.SendPropertyChanging();
					this._Religion = value;
					this.SendPropertyChanged("Religion");
					this.OnReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirhtDateG", DbType="Date")]
		public System.Nullable<System.DateTime> BirhtDateG
		{
			get
			{
				return this._BirhtDateG;
			}
			set
			{
				if ((this._BirhtDateG != value))
				{
					this.OnBirhtDateGChanging(value);
					this.SendPropertyChanging();
					this._BirhtDateG = value;
					this.SendPropertyChanged("BirhtDateG");
					this.OnBirhtDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirhtDateH", DbType="Date")]
		public System.Nullable<System.DateTime> BirhtDateH
		{
			get
			{
				return this._BirhtDateH;
			}
			set
			{
				if ((this._BirhtDateH != value))
				{
					this.OnBirhtDateHChanging(value);
					this.SendPropertyChanging();
					this._BirhtDateH = value;
					this.SendPropertyChanged("BirhtDateH");
					this.OnBirhtDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthPlace", DbType="NVarChar(150)")]
		public string BirthPlace
		{
			get
			{
				return this._BirthPlace;
			}
			set
			{
				if ((this._BirthPlace != value))
				{
					this.OnBirthPlaceChanging(value);
					this.SendPropertyChanging();
					this._BirthPlace = value;
					this.SendPropertyChanged("BirthPlace");
					this.OnBirthPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankNo", DbType="Int")]
		public System.Nullable<int> BankNo
		{
			get
			{
				return this._BankNo;
			}
			set
			{
				if ((this._BankNo != value))
				{
					this.OnBankNoChanging(value);
					this.SendPropertyChanging();
					this._BankNo = value;
					this.SendPropertyChanged("BankNo");
					this.OnBankNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBankNo", DbType="NVarChar(200)")]
		public string AccountBankNo
		{
			get
			{
				return this._AccountBankNo;
			}
			set
			{
				if ((this._AccountBankNo != value))
				{
					this.OnAccountBankNoChanging(value);
					this.SendPropertyChanging();
					this._AccountBankNo = value;
					this.SendPropertyChanged("AccountBankNo");
					this.OnAccountBankNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNum", DbType="NVarChar(100)")]
		public string PhoneNum
		{
			get
			{
				return this._PhoneNum;
			}
			set
			{
				if ((this._PhoneNum != value))
				{
					this.OnPhoneNumChanging(value);
					this.SendPropertyChanging();
					this._PhoneNum = value;
					this.SendPropertyChanged("PhoneNum");
					this.OnPhoneNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(100)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
		public System.Nullable<int> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SocialStatus", DbType="Int")]
		public System.Nullable<int> SocialStatus
		{
			get
			{
				return this._SocialStatus;
			}
			set
			{
				if ((this._SocialStatus != value))
				{
					this.OnSocialStatusChanging(value);
					this.SendPropertyChanging();
					this._SocialStatus = value;
					this.SendPropertyChanged("SocialStatus");
					this.OnSocialStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpStatus", DbType="Int")]
		public System.Nullable<int> EmpStatus
		{
			get
			{
				return this._EmpStatus;
			}
			set
			{
				if ((this._EmpStatus != value))
				{
					this.OnEmpStatusChanging(value);
					this.SendPropertyChanging();
					this._EmpStatus = value;
					this.SendPropertyChanged("EmpStatus");
					this.OnEmpStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeLocation", DbType="Int")]
		public System.Nullable<int> EmployeeLocation
		{
			get
			{
				return this._EmployeeLocation;
			}
			set
			{
				if ((this._EmployeeLocation != value))
				{
					this.OnEmployeeLocationChanging(value);
					this.SendPropertyChanging();
					this._EmployeeLocation = value;
					this.SendPropertyChanged("EmployeeLocation");
					this.OnEmployeeLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousExperince", DbType="Int")]
		public System.Nullable<int> PreviousExperince
		{
			get
			{
				return this._PreviousExperince;
			}
			set
			{
				if ((this._PreviousExperince != value))
				{
					this.OnPreviousExperinceChanging(value);
					this.SendPropertyChanging();
					this._PreviousExperince = value;
					this.SendPropertyChanged("PreviousExperince");
					this.OnPreviousExperinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectManager", DbType="NVarChar(50)")]
		public string DirectManager
		{
			get
			{
				return this._DirectManager;
			}
			set
			{
				if ((this._DirectManager != value))
				{
					this.OnDirectManagerChanging(value);
					this.SendPropertyChanging();
					this._DirectManager = value;
					this.SendPropertyChanged("DirectManager");
					this.OnDirectManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternativeEmp", DbType="NVarChar(50)")]
		public string AlternativeEmp
		{
			get
			{
				return this._AlternativeEmp;
			}
			set
			{
				if ((this._AlternativeEmp != value))
				{
					this.OnAlternativeEmpChanging(value);
					this.SendPropertyChanging();
					this._AlternativeEmp = value;
					this.SendPropertyChanged("AlternativeEmp");
					this.OnAlternativeEmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyStatus", DbType="Int")]
		public System.Nullable<int> FamilyStatus
		{
			get
			{
				return this._FamilyStatus;
			}
			set
			{
				if ((this._FamilyStatus != value))
				{
					this.OnFamilyStatusChanging(value);
					this.SendPropertyChanging();
					this._FamilyStatus = value;
					this.SendPropertyChanged("FamilyStatus");
					this.OnFamilyStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfChildern", DbType="Int")]
		public System.Nullable<int> NumberOfChildern
		{
			get
			{
				return this._NumberOfChildern;
			}
			set
			{
				if ((this._NumberOfChildern != value))
				{
					this.OnNumberOfChildernChanging(value);
					this.SendPropertyChanging();
					this._NumberOfChildern = value;
					this.SendPropertyChanged("NumberOfChildern");
					this.OnNumberOfChildernChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampNO", DbType="Int")]
		public System.Nullable<int> CampNO
		{
			get
			{
				return this._CampNO;
			}
			set
			{
				if ((this._CampNO != value))
				{
					this.OnCampNOChanging(value);
					this.SendPropertyChanging();
					this._CampNO = value;
					this.SendPropertyChanged("CampNO");
					this.OnCampNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNo", DbType="Int")]
		public System.Nullable<int> RoomNo
		{
			get
			{
				return this._RoomNo;
			}
			set
			{
				if ((this._RoomNo != value))
				{
					this.OnRoomNoChanging(value);
					this.SendPropertyChanging();
					this._RoomNo = value;
					this.SendPropertyChanged("RoomNo");
					this.OnRoomNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAddress", DbType="NVarChar(150)")]
		public string CurrentAddress
		{
			get
			{
				return this._CurrentAddress;
			}
			set
			{
				if ((this._CurrentAddress != value))
				{
					this.OnCurrentAddressChanging(value);
					this.SendPropertyChanging();
					this._CurrentAddress = value;
					this.SendPropertyChanged("CurrentAddress");
					this.OnCurrentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentAddress", DbType="NVarChar(150)")]
		public string PermanentAddress
		{
			get
			{
				return this._PermanentAddress;
			}
			set
			{
				if ((this._PermanentAddress != value))
				{
					this.OnPermanentAddressChanging(value);
					this.SendPropertyChanging();
					this._PermanentAddress = value;
					this.SendPropertyChanged("PermanentAddress");
					this.OnPermanentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisaDetailID", DbType="Int")]
		public System.Nullable<int> VisaDetailID
		{
			get
			{
				return this._VisaDetailID;
			}
			set
			{
				if ((this._VisaDetailID != value))
				{
					this.OnVisaDetailIDChanging(value);
					this.SendPropertyChanging();
					this._VisaDetailID = value;
					this.SendPropertyChanged("VisaDetailID");
					this.OnVisaDetailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorderNo", DbType="NVarChar(30)")]
		public string BorderNo
		{
			get
			{
				return this._BorderNo;
			}
			set
			{
				if ((this._BorderNo != value))
				{
					this.OnBorderNoChanging(value);
					this.SendPropertyChanging();
					this._BorderNo = value;
					this.SendPropertyChanged("BorderNo");
					this.OnBorderNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDateH", DbType="Date")]
		public System.Nullable<System.DateTime> EntryDateH
		{
			get
			{
				return this._EntryDateH;
			}
			set
			{
				if ((this._EntryDateH != value))
				{
					this.OnEntryDateHChanging(value);
					this.SendPropertyChanging();
					this._EntryDateH = value;
					this.SendPropertyChanged("EntryDateH");
					this.OnEntryDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDateG", DbType="Date")]
		public System.Nullable<System.DateTime> EntryDateG
		{
			get
			{
				return this._EntryDateG;
			}
			set
			{
				if ((this._EntryDateG != value))
				{
					this.OnEntryDateGChanging(value);
					this.SendPropertyChanging();
					this._EntryDateG = value;
					this.SendPropertyChanged("EntryDateG");
					this.OnEntryDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryPlace", DbType="Int")]
		public System.Nullable<int> EntryPlace
		{
			get
			{
				return this._EntryPlace;
			}
			set
			{
				if ((this._EntryPlace != value))
				{
					this.OnEntryPlaceChanging(value);
					this.SendPropertyChanging();
					this._EntryPlace = value;
					this.SendPropertyChanged("EntryPlace");
					this.OnEntryPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNo", DbType="NVarChar(30)")]
		public string PassportNo
		{
			get
			{
				return this._PassportNo;
			}
			set
			{
				if ((this._PassportNo != value))
				{
					this.OnPassportNoChanging(value);
					this.SendPropertyChanging();
					this._PassportNo = value;
					this.SendPropertyChanged("PassportNo");
					this.OnPassportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportIssueDateG", DbType="Date")]
		public System.Nullable<System.DateTime> PassportIssueDateG
		{
			get
			{
				return this._PassportIssueDateG;
			}
			set
			{
				if ((this._PassportIssueDateG != value))
				{
					this.OnPassportIssueDateGChanging(value);
					this.SendPropertyChanging();
					this._PassportIssueDateG = value;
					this.SendPropertyChanged("PassportIssueDateG");
					this.OnPassportIssueDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportIssueDateH", DbType="Date")]
		public System.Nullable<System.DateTime> PassportIssueDateH
		{
			get
			{
				return this._PassportIssueDateH;
			}
			set
			{
				if ((this._PassportIssueDateH != value))
				{
					this.OnPassportIssueDateHChanging(value);
					this.SendPropertyChanging();
					this._PassportIssueDateH = value;
					this.SendPropertyChanged("PassportIssueDateH");
					this.OnPassportIssueDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportExpiryDateG", DbType="Date")]
		public System.Nullable<System.DateTime> PassportExpiryDateG
		{
			get
			{
				return this._PassportExpiryDateG;
			}
			set
			{
				if ((this._PassportExpiryDateG != value))
				{
					this.OnPassportExpiryDateGChanging(value);
					this.SendPropertyChanging();
					this._PassportExpiryDateG = value;
					this.SendPropertyChanged("PassportExpiryDateG");
					this.OnPassportExpiryDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportExpiryDateH", DbType="Date")]
		public System.Nullable<System.DateTime> PassportExpiryDateH
		{
			get
			{
				return this._PassportExpiryDateH;
			}
			set
			{
				if ((this._PassportExpiryDateH != value))
				{
					this.OnPassportExpiryDateHChanging(value);
					this.SendPropertyChanging();
					this._PassportExpiryDateH = value;
					this.SendPropertyChanged("PassportExpiryDateH");
					this.OnPassportExpiryDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportIssuePlace", DbType="Int")]
		public System.Nullable<int> PassportIssuePlace
		{
			get
			{
				return this._PassportIssuePlace;
			}
			set
			{
				if ((this._PassportIssuePlace != value))
				{
					this.OnPassportIssuePlaceChanging(value);
					this.SendPropertyChanging();
					this._PassportIssuePlace = value;
					this.SendPropertyChanged("PassportIssuePlace");
					this.OnPassportIssuePlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaNo", DbType="NVarChar(30)")]
		public string IqamaNo
		{
			get
			{
				return this._IqamaNo;
			}
			set
			{
				if ((this._IqamaNo != value))
				{
					this.OnIqamaNoChanging(value);
					this.SendPropertyChanging();
					this._IqamaNo = value;
					this.SendPropertyChanged("IqamaNo");
					this.OnIqamaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaIssueDateH", DbType="Date")]
		public System.Nullable<System.DateTime> IqamaIssueDateH
		{
			get
			{
				return this._IqamaIssueDateH;
			}
			set
			{
				if ((this._IqamaIssueDateH != value))
				{
					this.OnIqamaIssueDateHChanging(value);
					this.SendPropertyChanging();
					this._IqamaIssueDateH = value;
					this.SendPropertyChanged("IqamaIssueDateH");
					this.OnIqamaIssueDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaIssueDateG", DbType="Date")]
		public System.Nullable<System.DateTime> IqamaIssueDateG
		{
			get
			{
				return this._IqamaIssueDateG;
			}
			set
			{
				if ((this._IqamaIssueDateG != value))
				{
					this.OnIqamaIssueDateGChanging(value);
					this.SendPropertyChanging();
					this._IqamaIssueDateG = value;
					this.SendPropertyChanged("IqamaIssueDateG");
					this.OnIqamaIssueDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaExpiryDateH", DbType="Date")]
		public System.Nullable<System.DateTime> IqamaExpiryDateH
		{
			get
			{
				return this._IqamaExpiryDateH;
			}
			set
			{
				if ((this._IqamaExpiryDateH != value))
				{
					this.OnIqamaExpiryDateHChanging(value);
					this.SendPropertyChanging();
					this._IqamaExpiryDateH = value;
					this.SendPropertyChanged("IqamaExpiryDateH");
					this.OnIqamaExpiryDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaExpiryDateG", DbType="Date")]
		public System.Nullable<System.DateTime> IqamaExpiryDateG
		{
			get
			{
				return this._IqamaExpiryDateG;
			}
			set
			{
				if ((this._IqamaExpiryDateG != value))
				{
					this.OnIqamaExpiryDateGChanging(value);
					this.SendPropertyChanging();
					this._IqamaExpiryDateG = value;
					this.SendPropertyChanged("IqamaExpiryDateG");
					this.OnIqamaExpiryDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaIssuePlace", DbType="Int")]
		public System.Nullable<int> IqamaIssuePlace
		{
			get
			{
				return this._IqamaIssuePlace;
			}
			set
			{
				if ((this._IqamaIssuePlace != value))
				{
					this.OnIqamaIssuePlaceChanging(value);
					this.SendPropertyChanging();
					this._IqamaIssuePlace = value;
					this.SendPropertyChanged("IqamaIssuePlace");
					this.OnIqamaIssuePlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPNo", DbType="NVarChar(30)")]
		public string WPNo
		{
			get
			{
				return this._WPNo;
			}
			set
			{
				if ((this._WPNo != value))
				{
					this.OnWPNoChanging(value);
					this.SendPropertyChanging();
					this._WPNo = value;
					this.SendPropertyChanged("WPNo");
					this.OnWPNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPIssueDateH", DbType="Date")]
		public System.Nullable<System.DateTime> WPIssueDateH
		{
			get
			{
				return this._WPIssueDateH;
			}
			set
			{
				if ((this._WPIssueDateH != value))
				{
					this.OnWPIssueDateHChanging(value);
					this.SendPropertyChanging();
					this._WPIssueDateH = value;
					this.SendPropertyChanged("WPIssueDateH");
					this.OnWPIssueDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPIssueDateG", DbType="Date")]
		public System.Nullable<System.DateTime> WPIssueDateG
		{
			get
			{
				return this._WPIssueDateG;
			}
			set
			{
				if ((this._WPIssueDateG != value))
				{
					this.OnWPIssueDateGChanging(value);
					this.SendPropertyChanging();
					this._WPIssueDateG = value;
					this.SendPropertyChanged("WPIssueDateG");
					this.OnWPIssueDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPExpiryDateH", DbType="Date")]
		public System.Nullable<System.DateTime> WPExpiryDateH
		{
			get
			{
				return this._WPExpiryDateH;
			}
			set
			{
				if ((this._WPExpiryDateH != value))
				{
					this.OnWPExpiryDateHChanging(value);
					this.SendPropertyChanging();
					this._WPExpiryDateH = value;
					this.SendPropertyChanged("WPExpiryDateH");
					this.OnWPExpiryDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPExpiryDateG", DbType="Date")]
		public System.Nullable<System.DateTime> WPExpiryDateG
		{
			get
			{
				return this._WPExpiryDateG;
			}
			set
			{
				if ((this._WPExpiryDateG != value))
				{
					this.OnWPExpiryDateGChanging(value);
					this.SendPropertyChanging();
					this._WPExpiryDateG = value;
					this.SendPropertyChanged("WPExpiryDateG");
					this.OnWPExpiryDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPPlace", DbType="Int")]
		public System.Nullable<int> WPPlace
		{
			get
			{
				return this._WPPlace;
			}
			set
			{
				if ((this._WPPlace != value))
				{
					this.OnWPPlaceChanging(value);
					this.SendPropertyChanging();
					this._WPPlace = value;
					this.SendPropertyChanged("WPPlace");
					this.OnWPPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriveLicenseNo", DbType="NVarChar(30)")]
		public string DriveLicenseNo
		{
			get
			{
				return this._DriveLicenseNo;
			}
			set
			{
				if ((this._DriveLicenseNo != value))
				{
					this.OnDriveLicenseNoChanging(value);
					this.SendPropertyChanging();
					this._DriveLicenseNo = value;
					this.SendPropertyChanged("DriveLicenseNo");
					this.OnDriveLicenseNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLIssueDateH", DbType="Date")]
		public System.Nullable<System.DateTime> DLIssueDateH
		{
			get
			{
				return this._DLIssueDateH;
			}
			set
			{
				if ((this._DLIssueDateH != value))
				{
					this.OnDLIssueDateHChanging(value);
					this.SendPropertyChanging();
					this._DLIssueDateH = value;
					this.SendPropertyChanged("DLIssueDateH");
					this.OnDLIssueDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLIssueDateG", DbType="Date")]
		public System.Nullable<System.DateTime> DLIssueDateG
		{
			get
			{
				return this._DLIssueDateG;
			}
			set
			{
				if ((this._DLIssueDateG != value))
				{
					this.OnDLIssueDateGChanging(value);
					this.SendPropertyChanging();
					this._DLIssueDateG = value;
					this.SendPropertyChanged("DLIssueDateG");
					this.OnDLIssueDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLExpiryDateH", DbType="Date")]
		public System.Nullable<System.DateTime> DLExpiryDateH
		{
			get
			{
				return this._DLExpiryDateH;
			}
			set
			{
				if ((this._DLExpiryDateH != value))
				{
					this.OnDLExpiryDateHChanging(value);
					this.SendPropertyChanging();
					this._DLExpiryDateH = value;
					this.SendPropertyChanged("DLExpiryDateH");
					this.OnDLExpiryDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLExpiryDateG", DbType="Date")]
		public System.Nullable<System.DateTime> DLExpiryDateG
		{
			get
			{
				return this._DLExpiryDateG;
			}
			set
			{
				if ((this._DLExpiryDateG != value))
				{
					this.OnDLExpiryDateGChanging(value);
					this.SendPropertyChanging();
					this._DLExpiryDateG = value;
					this.SendPropertyChanged("DLExpiryDateG");
					this.OnDLExpiryDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLPlace", DbType="Int")]
		public System.Nullable<int> DLPlace
		{
			get
			{
				return this._DLPlace;
			}
			set
			{
				if ((this._DLPlace != value))
				{
					this.OnDLPlaceChanging(value);
					this.SendPropertyChanging();
					this._DLPlace = value;
					this.SendPropertyChanged("DLPlace");
					this.OnDLPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLCalss", DbType="Int")]
		public System.Nullable<int> DLCalss
		{
			get
			{
				return this._DLCalss;
			}
			set
			{
				if ((this._DLCalss != value))
				{
					this.OnDLCalssChanging(value);
					this.SendPropertyChanging();
					this._DLCalss = value;
					this.SendPropertyChanged("DLCalss");
					this.OnDLCalssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GosiNo", DbType="NVarChar(30)")]
		public string GosiNo
		{
			get
			{
				return this._GosiNo;
			}
			set
			{
				if ((this._GosiNo != value))
				{
					this.OnGosiNoChanging(value);
					this.SendPropertyChanging();
					this._GosiNo = value;
					this.SendPropertyChanged("GosiNo");
					this.OnGosiNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GosiIssueDateG", DbType="Date")]
		public System.Nullable<System.DateTime> GosiIssueDateG
		{
			get
			{
				return this._GosiIssueDateG;
			}
			set
			{
				if ((this._GosiIssueDateG != value))
				{
					this.OnGosiIssueDateGChanging(value);
					this.SendPropertyChanging();
					this._GosiIssueDateG = value;
					this.SendPropertyChanged("GosiIssueDateG");
					this.OnGosiIssueDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GosiIssueDateH", DbType="Date")]
		public System.Nullable<System.DateTime> GosiIssueDateH
		{
			get
			{
				return this._GosiIssueDateH;
			}
			set
			{
				if ((this._GosiIssueDateH != value))
				{
					this.OnGosiIssueDateHChanging(value);
					this.SendPropertyChanging();
					this._GosiIssueDateH = value;
					this.SendPropertyChanged("GosiIssueDateH");
					this.OnGosiIssueDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GosiExpiryDateG", DbType="Date")]
		public System.Nullable<System.DateTime> GosiExpiryDateG
		{
			get
			{
				return this._GosiExpiryDateG;
			}
			set
			{
				if ((this._GosiExpiryDateG != value))
				{
					this.OnGosiExpiryDateGChanging(value);
					this.SendPropertyChanging();
					this._GosiExpiryDateG = value;
					this.SendPropertyChanged("GosiExpiryDateG");
					this.OnGosiExpiryDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GosiExpiryDateH", DbType="Date")]
		public System.Nullable<System.DateTime> GosiExpiryDateH
		{
			get
			{
				return this._GosiExpiryDateH;
			}
			set
			{
				if ((this._GosiExpiryDateH != value))
				{
					this.OnGosiExpiryDateHChanging(value);
					this.SendPropertyChanging();
					this._GosiExpiryDateH = value;
					this.SendPropertyChanged("GosiExpiryDateH");
					this.OnGosiExpiryDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GosiPlace", DbType="Int")]
		public System.Nullable<int> GosiPlace
		{
			get
			{
				return this._GosiPlace;
			}
			set
			{
				if ((this._GosiPlace != value))
				{
					this.OnGosiPlaceChanging(value);
					this.SendPropertyChanging();
					this._GosiPlace = value;
					this.SendPropertyChanged("GosiPlace");
					this.OnGosiPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GosiAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GosiAmount
		{
			get
			{
				return this._GosiAmount;
			}
			set
			{
				if ((this._GosiAmount != value))
				{
					this.OnGosiAmountChanging(value);
					this.SendPropertyChanging();
					this._GosiAmount = value;
					this.SendPropertyChanged("GosiAmount");
					this.OnGosiAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InjuryCount", DbType="Int")]
		public System.Nullable<int> InjuryCount
		{
			get
			{
				return this._InjuryCount;
			}
			set
			{
				if ((this._InjuryCount != value))
				{
					this.OnInjuryCountChanging(value);
					this.SendPropertyChanging();
					this._InjuryCount = value;
					this.SendPropertyChanged("InjuryCount");
					this.OnInjuryCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthPlaceCity", DbType="Int")]
		public System.Nullable<int> BirthPlaceCity
		{
			get
			{
				return this._BirthPlaceCity;
			}
			set
			{
				if ((this._BirthPlaceCity != value))
				{
					this.OnBirthPlaceCityChanging(value);
					this.SendPropertyChanging();
					this._BirthPlaceCity = value;
					this.SendPropertyChanged("BirthPlaceCity");
					this.OnBirthPlaceCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="NVarChar(500)")]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkOrderID", DbType="NVarChar(50)")]
		public string WorkOrderID
		{
			get
			{
				return this._WorkOrderID;
			}
			set
			{
				if ((this._WorkOrderID != value))
				{
					this.OnWorkOrderIDChanging(value);
					this.SendPropertyChanging();
					this._WorkOrderID = value;
					this.SendPropertyChanged("WorkOrderID");
					this.OnWorkOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfArchive", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfArchive
		{
			get
			{
				return this._DateOfArchive;
			}
			set
			{
				if ((this._DateOfArchive != value))
				{
					this.OnDateOfArchiveChanging(value);
					this.SendPropertyChanging();
					this._DateOfArchive = value;
					this.SendPropertyChanged("DateOfArchive");
					this.OnDateOfArchiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArchiveUserID", DbType="Int")]
		public System.Nullable<int> ArchiveUserID
		{
			get
			{
				return this._ArchiveUserID;
			}
			set
			{
				if ((this._ArchiveUserID != value))
				{
					this.OnArchiveUserIDChanging(value);
					this.SendPropertyChanging();
					this._ArchiveUserID = value;
					this.SendPropertyChanged("ArchiveUserID");
					this.OnArchiveUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hired", DbType="Bit")]
		public System.Nullable<bool> Hired
		{
			get
			{
				return this._Hired;
			}
			set
			{
				if ((this._Hired != value))
				{
					this.OnHiredChanging(value);
					this.SendPropertyChanging();
					this._Hired = value;
					this.SendPropertyChanged("Hired");
					this.OnHiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff", DbType="Int")]
		public System.Nullable<int> Staff
		{
			get
			{
				return this._Staff;
			}
			set
			{
				if ((this._Staff != value))
				{
					this.OnStaffChanging(value);
					this.SendPropertyChanging();
					this._Staff = value;
					this.SendPropertyChanged("Staff");
					this.OnStaffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurancePolicyNO", DbType="NVarChar(75)")]
		public string InsurancePolicyNO
		{
			get
			{
				return this._InsurancePolicyNO;
			}
			set
			{
				if ((this._InsurancePolicyNO != value))
				{
					this.OnInsurancePolicyNOChanging(value);
					this.SendPropertyChanging();
					this._InsurancePolicyNO = value;
					this.SendPropertyChanged("InsurancePolicyNO");
					this.OnInsurancePolicyNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceReferenceNo", DbType="NVarChar(75)")]
		public string InsuranceReferenceNo
		{
			get
			{
				return this._InsuranceReferenceNo;
			}
			set
			{
				if ((this._InsuranceReferenceNo != value))
				{
					this.OnInsuranceReferenceNoChanging(value);
					this.SendPropertyChanging();
					this._InsuranceReferenceNo = value;
					this.SendPropertyChanged("InsuranceReferenceNo");
					this.OnInsuranceReferenceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceMembershipNO", DbType="NVarChar(75)")]
		public string InsuranceMembershipNO
		{
			get
			{
				return this._InsuranceMembershipNO;
			}
			set
			{
				if ((this._InsuranceMembershipNO != value))
				{
					this.OnInsuranceMembershipNOChanging(value);
					this.SendPropertyChanging();
					this._InsuranceMembershipNO = value;
					this.SendPropertyChanged("InsuranceMembershipNO");
					this.OnInsuranceMembershipNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceClass", DbType="Int")]
		public System.Nullable<int> InsuranceClass
		{
			get
			{
				return this._InsuranceClass;
			}
			set
			{
				if ((this._InsuranceClass != value))
				{
					this.OnInsuranceClassChanging(value);
					this.SendPropertyChanging();
					this._InsuranceClass = value;
					this.SendPropertyChanged("InsuranceClass");
					this.OnInsuranceClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceJoiningDate", DbType="Date")]
		public System.Nullable<System.DateTime> InsuranceJoiningDate
		{
			get
			{
				return this._InsuranceJoiningDate;
			}
			set
			{
				if ((this._InsuranceJoiningDate != value))
				{
					this.OnInsuranceJoiningDateChanging(value);
					this.SendPropertyChanging();
					this._InsuranceJoiningDate = value;
					this.SendPropertyChanged("InsuranceJoiningDate");
					this.OnInsuranceJoiningDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceDisJoiningDate", DbType="Date")]
		public System.Nullable<System.DateTime> InsuranceDisJoiningDate
		{
			get
			{
				return this._InsuranceDisJoiningDate;
			}
			set
			{
				if ((this._InsuranceDisJoiningDate != value))
				{
					this.OnInsuranceDisJoiningDateChanging(value);
					this.SendPropertyChanging();
					this._InsuranceDisJoiningDate = value;
					this.SendPropertyChanged("InsuranceDisJoiningDate");
					this.OnInsuranceDisJoiningDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceNotes", DbType="NVarChar(MAX)")]
		public string InsuranceNotes
		{
			get
			{
				return this._InsuranceNotes;
			}
			set
			{
				if ((this._InsuranceNotes != value))
				{
					this.OnInsuranceNotesChanging(value);
					this.SendPropertyChanging();
					this._InsuranceNotes = value;
					this.SendPropertyChanged("InsuranceNotes");
					this.OnInsuranceNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentCategory", DbType="Int")]
		public System.Nullable<int> CurrentCategory
		{
			get
			{
				return this._CurrentCategory;
			}
			set
			{
				if ((this._CurrentCategory != value))
				{
					this.OnCurrentCategoryChanging(value);
					this.SendPropertyChanging();
					this._CurrentCategory = value;
					this.SendPropertyChanged("CurrentCategory");
					this.OnCurrentCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="NVarChar(50)")]
		public string DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this.OnDepartmentIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmentID = value;
					this.SendPropertyChanged("DepartmentID");
					this.OnDepartmentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodGroup", DbType="NVarChar(10)")]
		public string BloodGroup
		{
			get
			{
				return this._BloodGroup;
			}
			set
			{
				if ((this._BloodGroup != value))
				{
					this.OnBloodGroupChanging(value);
					this.SendPropertyChanging();
					this._BloodGroup = value;
					this.SendPropertyChanged("BloodGroup");
					this.OnBloodGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedVacationDate", DbType="Date")]
		public System.Nullable<System.DateTime> ExpectedVacationDate
		{
			get
			{
				return this._ExpectedVacationDate;
			}
			set
			{
				if ((this._ExpectedVacationDate != value))
				{
					this.OnExpectedVacationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpectedVacationDate = value;
					this.SendPropertyChanged("ExpectedVacationDate");
					this.OnExpectedVacationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedVacationDateH", DbType="Date")]
		public System.Nullable<System.DateTime> ExpectedVacationDateH
		{
			get
			{
				return this._ExpectedVacationDateH;
			}
			set
			{
				if ((this._ExpectedVacationDateH != value))
				{
					this.OnExpectedVacationDateHChanging(value);
					this.SendPropertyChanging();
					this._ExpectedVacationDateH = value;
					this.SendPropertyChanged("ExpectedVacationDateH");
					this.OnExpectedVacationDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorNoOld", DbType="Int")]
		public System.Nullable<int> SponsorNoOld
		{
			get
			{
				return this._SponsorNoOld;
			}
			set
			{
				if ((this._SponsorNoOld != value))
				{
					this.OnSponsorNoOldChanging(value);
					this.SendPropertyChanging();
					this._SponsorNoOld = value;
					this.SendPropertyChanged("SponsorNoOld");
					this.OnSponsorNoOldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageID", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ImageID
		{
			get
			{
				return this._ImageID;
			}
			set
			{
				if ((this._ImageID != value))
				{
					this.OnImageIDChanging(value);
					this.SendPropertyChanging();
					this._ImageID = value;
					this.SendPropertyChanged("ImageID");
					this.OnImageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusDate", DbType="Date")]
		public System.Nullable<System.DateTime> StatusDate
		{
			get
			{
				return this._StatusDate;
			}
			set
			{
				if ((this._StatusDate != value))
				{
					this.OnStatusDateChanging(value);
					this.SendPropertyChanging();
					this._StatusDate = value;
					this.SendPropertyChanged("StatusDate");
					this.OnStatusDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankNo2", DbType="Int")]
		public System.Nullable<int> BankNo2
		{
			get
			{
				return this._BankNo2;
			}
			set
			{
				if ((this._BankNo2 != value))
				{
					this.OnBankNo2Changing(value);
					this.SendPropertyChanging();
					this._BankNo2 = value;
					this.SendPropertyChanged("BankNo2");
					this.OnBankNo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBankNo2", DbType="NVarChar(200)")]
		public string AccountBankNo2
		{
			get
			{
				return this._AccountBankNo2;
			}
			set
			{
				if ((this._AccountBankNo2 != value))
				{
					this.OnAccountBankNo2Changing(value);
					this.SendPropertyChanging();
					this._AccountBankNo2 = value;
					this.SendPropertyChanged("AccountBankNo2");
					this.OnAccountBankNo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDateBank2", DbType="Date")]
		public System.Nullable<System.DateTime> UpdatedDateBank2
		{
			get
			{
				return this._UpdatedDateBank2;
			}
			set
			{
				if ((this._UpdatedDateBank2 != value))
				{
					this.OnUpdatedDateBank2Changing(value);
					this.SendPropertyChanging();
					this._UpdatedDateBank2 = value;
					this.SendPropertyChanged("UpdatedDateBank2");
					this.OnUpdatedDateBank2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankNo3", DbType="Int")]
		public System.Nullable<int> BankNo3
		{
			get
			{
				return this._BankNo3;
			}
			set
			{
				if ((this._BankNo3 != value))
				{
					this.OnBankNo3Changing(value);
					this.SendPropertyChanging();
					this._BankNo3 = value;
					this.SendPropertyChanged("BankNo3");
					this.OnBankNo3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBankNo3", DbType="NVarChar(200)")]
		public string AccountBankNo3
		{
			get
			{
				return this._AccountBankNo3;
			}
			set
			{
				if ((this._AccountBankNo3 != value))
				{
					this.OnAccountBankNo3Changing(value);
					this.SendPropertyChanging();
					this._AccountBankNo3 = value;
					this.SendPropertyChanged("AccountBankNo3");
					this.OnAccountBankNo3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDateBank3", DbType="Date")]
		public System.Nullable<System.DateTime> UpdatedDateBank3
		{
			get
			{
				return this._UpdatedDateBank3;
			}
			set
			{
				if ((this._UpdatedDateBank3 != value))
				{
					this.OnUpdatedDateBank3Changing(value);
					this.SendPropertyChanging();
					this._UpdatedDateBank3 = value;
					this.SendPropertyChanged("UpdatedDateBank3");
					this.OnUpdatedDateBank3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESBDate", DbType="Date")]
		public System.Nullable<System.DateTime> ESBDate
		{
			get
			{
				return this._ESBDate;
			}
			set
			{
				if ((this._ESBDate != value))
				{
					this.OnESBDateChanging(value);
					this.SendPropertyChanging();
					this._ESBDate = value;
					this.SendPropertyChanged("ESBDate");
					this.OnESBDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guaranteed", DbType="NVarChar(50)")]
		public string Guaranteed
		{
			get
			{
				return this._Guaranteed;
			}
			set
			{
				if ((this._Guaranteed != value))
				{
					this.OnGuaranteedChanging(value);
					this.SendPropertyChanging();
					this._Guaranteed = value;
					this.SendPropertyChanged("Guaranteed");
					this.OnGuaranteedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfGuarantee", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfGuarantee
		{
			get
			{
				return this._DateOfGuarantee;
			}
			set
			{
				if ((this._DateOfGuarantee != value))
				{
					this.OnDateOfGuaranteeChanging(value);
					this.SendPropertyChanging();
					this._DateOfGuarantee = value;
					this.SendPropertyChanged("DateOfGuarantee");
					this.OnDateOfGuaranteeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurposeOfGuarantee", DbType="NVarChar(500)")]
		public string PurposeOfGuarantee
		{
			get
			{
				return this._PurposeOfGuarantee;
			}
			set
			{
				if ((this._PurposeOfGuarantee != value))
				{
					this.OnPurposeOfGuaranteeChanging(value);
					this.SendPropertyChanging();
					this._PurposeOfGuarantee = value;
					this.SendPropertyChanged("PurposeOfGuarantee");
					this.OnPurposeOfGuaranteeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountOfGuarantee", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AmountOfGuarantee
		{
			get
			{
				return this._AmountOfGuarantee;
			}
			set
			{
				if ((this._AmountOfGuarantee != value))
				{
					this.OnAmountOfGuaranteeChanging(value);
					this.SendPropertyChanging();
					this._AmountOfGuarantee = value;
					this.SendPropertyChanged("AmountOfGuarantee");
					this.OnAmountOfGuaranteeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBANBank1", DbType="NVarChar(500)")]
		public string IBANBank1
		{
			get
			{
				return this._IBANBank1;
			}
			set
			{
				if ((this._IBANBank1 != value))
				{
					this.OnIBANBank1Changing(value);
					this.SendPropertyChanging();
					this._IBANBank1 = value;
					this.SendPropertyChanged("IBANBank1");
					this.OnIBANBank1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBANBank2", DbType="NVarChar(500)")]
		public string IBANBank2
		{
			get
			{
				return this._IBANBank2;
			}
			set
			{
				if ((this._IBANBank2 != value))
				{
					this.OnIBANBank2Changing(value);
					this.SendPropertyChanging();
					this._IBANBank2 = value;
					this.SendPropertyChanged("IBANBank2");
					this.OnIBANBank2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBANBank3", DbType="NVarChar(500)")]
		public string IBANBank3
		{
			get
			{
				return this._IBANBank3;
			}
			set
			{
				if ((this._IBANBank3 != value))
				{
					this.OnIBANBank3Changing(value);
					this.SendPropertyChanging();
					this._IBANBank3 = value;
					this.SendPropertyChanged("IBANBank3");
					this.OnIBANBank3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResidentIdentityExpiryDateH", DbType="Date")]
		public System.Nullable<System.DateTime> ResidentIdentityExpiryDateH
		{
			get
			{
				return this._ResidentIdentityExpiryDateH;
			}
			set
			{
				if ((this._ResidentIdentityExpiryDateH != value))
				{
					this.OnResidentIdentityExpiryDateHChanging(value);
					this.SendPropertyChanging();
					this._ResidentIdentityExpiryDateH = value;
					this.SendPropertyChanged("ResidentIdentityExpiryDateH");
					this.OnResidentIdentityExpiryDateHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResidentIdentityExpiryDateG", DbType="Date")]
		public System.Nullable<System.DateTime> ResidentIdentityExpiryDateG
		{
			get
			{
				return this._ResidentIdentityExpiryDateG;
			}
			set
			{
				if ((this._ResidentIdentityExpiryDateG != value))
				{
					this.OnResidentIdentityExpiryDateGChanging(value);
					this.SendPropertyChanging();
					this._ResidentIdentityExpiryDateG = value;
					this.SendPropertyChanged("ResidentIdentityExpiryDateG");
					this.OnResidentIdentityExpiryDateGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoucherNo", DbType="NVarChar(200)")]
		public string VoucherNo
		{
			get
			{
				return this._VoucherNo;
			}
			set
			{
				if ((this._VoucherNo != value))
				{
					this.OnVoucherNoChanging(value);
					this.SendPropertyChanging();
					this._VoucherNo = value;
					this.SendPropertyChanged("VoucherNo");
					this.OnVoucherNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedReturnDateOfGuaranteed", DbType="Date")]
		public System.Nullable<System.DateTime> ExpectedReturnDateOfGuaranteed
		{
			get
			{
				return this._ExpectedReturnDateOfGuaranteed;
			}
			set
			{
				if ((this._ExpectedReturnDateOfGuaranteed != value))
				{
					this.OnExpectedReturnDateOfGuaranteedChanging(value);
					this.SendPropertyChanging();
					this._ExpectedReturnDateOfGuaranteed = value;
					this.SendPropertyChanged("ExpectedReturnDateOfGuaranteed");
					this.OnExpectedReturnDateOfGuaranteedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualReturnDateOfGuaranteed", DbType="Date")]
		public System.Nullable<System.DateTime> ActualReturnDateOfGuaranteed
		{
			get
			{
				return this._ActualReturnDateOfGuaranteed;
			}
			set
			{
				if ((this._ActualReturnDateOfGuaranteed != value))
				{
					this.OnActualReturnDateOfGuaranteedChanging(value);
					this.SendPropertyChanging();
					this._ActualReturnDateOfGuaranteed = value;
					this.SendPropertyChanged("ActualReturnDateOfGuaranteed");
					this.OnActualReturnDateOfGuaranteedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionTaken", DbType="NVarChar(500)")]
		public string ActionTaken
		{
			get
			{
				return this._ActionTaken;
			}
			set
			{
				if ((this._ActionTaken != value))
				{
					this.OnActionTakenChanging(value);
					this.SendPropertyChanging();
					this._ActionTaken = value;
					this.SendPropertyChanged("ActionTaken");
					this.OnActionTakenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisaExpiryDateOfGuaranteed", DbType="Date")]
		public System.Nullable<System.DateTime> VisaExpiryDateOfGuaranteed
		{
			get
			{
				return this._VisaExpiryDateOfGuaranteed;
			}
			set
			{
				if ((this._VisaExpiryDateOfGuaranteed != value))
				{
					this.OnVisaExpiryDateOfGuaranteedChanging(value);
					this.SendPropertyChanging();
					this._VisaExpiryDateOfGuaranteed = value;
					this.SendPropertyChanged("VisaExpiryDateOfGuaranteed");
					this.OnVisaExpiryDateOfGuaranteedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPermitCost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> WorkPermitCost
		{
			get
			{
				return this._WorkPermitCost;
			}
			set
			{
				if ((this._WorkPermitCost != value))
				{
					this.OnWorkPermitCostChanging(value);
					this.SendPropertyChanging();
					this._WorkPermitCost = value;
					this.SendPropertyChanged("WorkPermitCost");
					this.OnWorkPermitCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPermitNote", DbType="NVarChar(500)")]
		public string WorkPermitNote
		{
			get
			{
				return this._WorkPermitNote;
			}
			set
			{
				if ((this._WorkPermitNote != value))
				{
					this.OnWorkPermitNoteChanging(value);
					this.SendPropertyChanging();
					this._WorkPermitNote = value;
					this.SendPropertyChanged("WorkPermitNote");
					this.OnWorkPermitNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHrEmp_STblVoucher", Storage="_STblVouchers", ThisKey="EmpNo", OtherKey="Emp_Id")]
		public EntitySet<STblVoucher> STblVouchers
		{
			get
			{
				return this._STblVouchers;
			}
			set
			{
				this._STblVouchers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_STblVouchers(STblVoucher entity)
		{
			this.SendPropertyChanging();
			entity.TblHrEmp = this;
		}
		
		private void detach_STblVouchers(STblVoucher entity)
		{
			this.SendPropertyChanging();
			entity.TblHrEmp = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Emp")]
	public partial class View_Emp
	{
		
		private string _EmpNo;
		
		private string _FullNameArab;
		
		private string _FullNameEng;
		
		private string _IqamaNo;
		
		public View_Emp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this._EmpNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameArab", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FullNameArab
		{
			get
			{
				return this._FullNameArab;
			}
			set
			{
				if ((this._FullNameArab != value))
				{
					this._FullNameArab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FullNameEng
		{
			get
			{
				return this._FullNameEng;
			}
			set
			{
				if ((this._FullNameEng != value))
				{
					this._FullNameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaNo", DbType="NVarChar(30)")]
		public string IqamaNo
		{
			get
			{
				return this._IqamaNo;
			}
			set
			{
				if ((this._IqamaNo != value))
				{
					this._IqamaNo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STblVouchers")]
	public partial class STblVoucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Voucher_id;
		
		private string _Emp_Id;
		
		private System.Nullable<System.DateTime> _Payment_Date;
		
		private System.Nullable<System.DateTime> _Recived_Date;
		
		private string _amount;
		
		private string _Payment_Way;
		
		private string _type;
		
		private System.Nullable<bool> _is_Cheque;
		
		private System.Nullable<System.DateTime> _Cheque_date;
		
		private string _Cheque_No;
		
		private string _Cheque_Bank;
		
		private EntityRef<TblHrEmp> _TblHrEmp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVoucher_idChanging(string value);
    partial void OnVoucher_idChanged();
    partial void OnEmp_IdChanging(string value);
    partial void OnEmp_IdChanged();
    partial void OnPayment_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnPayment_DateChanged();
    partial void OnRecived_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRecived_DateChanged();
    partial void OnamountChanging(string value);
    partial void OnamountChanged();
    partial void OnPayment_WayChanging(string value);
    partial void OnPayment_WayChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onis_ChequeChanging(System.Nullable<bool> value);
    partial void Onis_ChequeChanged();
    partial void OnCheque_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnCheque_dateChanged();
    partial void OnCheque_NoChanging(string value);
    partial void OnCheque_NoChanged();
    partial void OnCheque_BankChanging(string value);
    partial void OnCheque_BankChanged();
    #endregion
		
		public STblVoucher()
		{
			this._TblHrEmp = default(EntityRef<TblHrEmp>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voucher_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Voucher_id
		{
			get
			{
				return this._Voucher_id;
			}
			set
			{
				if ((this._Voucher_id != value))
				{
					this.OnVoucher_idChanging(value);
					this.SendPropertyChanging();
					this._Voucher_id = value;
					this.SendPropertyChanged("Voucher_id");
					this.OnVoucher_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Id", DbType="NVarChar(50)")]
		public string Emp_Id
		{
			get
			{
				return this._Emp_Id;
			}
			set
			{
				if ((this._Emp_Id != value))
				{
					if (this._TblHrEmp.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmp_IdChanging(value);
					this.SendPropertyChanging();
					this._Emp_Id = value;
					this.SendPropertyChanged("Emp_Id");
					this.OnEmp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Payment_Date
		{
			get
			{
				return this._Payment_Date;
			}
			set
			{
				if ((this._Payment_Date != value))
				{
					this.OnPayment_DateChanging(value);
					this.SendPropertyChanging();
					this._Payment_Date = value;
					this.SendPropertyChanged("Payment_Date");
					this.OnPayment_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recived_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Recived_Date
		{
			get
			{
				return this._Recived_Date;
			}
			set
			{
				if ((this._Recived_Date != value))
				{
					this.OnRecived_DateChanging(value);
					this.SendPropertyChanging();
					this._Recived_Date = value;
					this.SendPropertyChanged("Recived_Date");
					this.OnRecived_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="NVarChar(50)")]
		public string amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Way", DbType="NVarChar(50)")]
		public string Payment_Way
		{
			get
			{
				return this._Payment_Way;
			}
			set
			{
				if ((this._Payment_Way != value))
				{
					this.OnPayment_WayChanging(value);
					this.SendPropertyChanging();
					this._Payment_Way = value;
					this.SendPropertyChanged("Payment_Way");
					this.OnPayment_WayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_Cheque", DbType="Bit")]
		public System.Nullable<bool> is_Cheque
		{
			get
			{
				return this._is_Cheque;
			}
			set
			{
				if ((this._is_Cheque != value))
				{
					this.Onis_ChequeChanging(value);
					this.SendPropertyChanging();
					this._is_Cheque = value;
					this.SendPropertyChanged("is_Cheque");
					this.Onis_ChequeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_date", DbType="Date")]
		public System.Nullable<System.DateTime> Cheque_date
		{
			get
			{
				return this._Cheque_date;
			}
			set
			{
				if ((this._Cheque_date != value))
				{
					this.OnCheque_dateChanging(value);
					this.SendPropertyChanging();
					this._Cheque_date = value;
					this.SendPropertyChanged("Cheque_date");
					this.OnCheque_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_No", DbType="NVarChar(50)")]
		public string Cheque_No
		{
			get
			{
				return this._Cheque_No;
			}
			set
			{
				if ((this._Cheque_No != value))
				{
					this.OnCheque_NoChanging(value);
					this.SendPropertyChanging();
					this._Cheque_No = value;
					this.SendPropertyChanged("Cheque_No");
					this.OnCheque_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_Bank", DbType="NVarChar(500)")]
		public string Cheque_Bank
		{
			get
			{
				return this._Cheque_Bank;
			}
			set
			{
				if ((this._Cheque_Bank != value))
				{
					this.OnCheque_BankChanging(value);
					this.SendPropertyChanging();
					this._Cheque_Bank = value;
					this.SendPropertyChanged("Cheque_Bank");
					this.OnCheque_BankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblHrEmp_STblVoucher", Storage="_TblHrEmp", ThisKey="Emp_Id", OtherKey="EmpNo", IsForeignKey=true, DeleteRule="CASCADE")]
		public TblHrEmp TblHrEmp
		{
			get
			{
				return this._TblHrEmp.Entity;
			}
			set
			{
				TblHrEmp previousValue = this._TblHrEmp.Entity;
				if (((previousValue != value) 
							|| (this._TblHrEmp.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblHrEmp.Entity = null;
						previousValue.STblVouchers.Remove(this);
					}
					this._TblHrEmp.Entity = value;
					if ((value != null))
					{
						value.STblVouchers.Add(this);
						this._Emp_Id = value.EmpNo;
					}
					else
					{
						this._Emp_Id = default(string);
					}
					this.SendPropertyChanged("TblHrEmp");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
