#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vouchar_Program.Voucher
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Vouchers")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTb_HrEmp(Tb_HrEmp instance);
    partial void UpdateTb_HrEmp(Tb_HrEmp instance);
    partial void DeleteTb_HrEmp(Tb_HrEmp instance);
    partial void InsertTb_Voucher(Tb_Voucher instance);
    partial void UpdateTb_Voucher(Tb_Voucher instance);
    partial void DeleteTb_Voucher(Tb_Voucher instance);
    partial void InsertVouchers_Type(Vouchers_Type instance);
    partial void UpdateVouchers_Type(Vouchers_Type instance);
    partial void DeleteVouchers_Type(Vouchers_Type instance);
    partial void InsertTb_Installmentubdate(Tb_Installmentubdate instance);
    partial void UpdateTb_Installmentubdate(Tb_Installmentubdate instance);
    partial void DeleteTb_Installmentubdate(Tb_Installmentubdate instance);
    partial void InsertTb_Installment(Tb_Installment instance);
    partial void UpdateTb_Installment(Tb_Installment instance);
    partial void DeleteTb_Installment(Tb_Installment instance);
    #endregion
		
		public LinqDataContext() : 
				base(global::Vouchar_Program.Properties.Settings.Default.TESTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tb_HrEmp> Tb_HrEmps
		{
			get
			{
				return this.GetTable<Tb_HrEmp>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Voucher> Tb_Vouchers
		{
			get
			{
				return this.GetTable<Tb_Voucher>();
			}
		}
		
		public System.Data.Linq.Table<Vouchers_Type> Vouchers_Types
		{
			get
			{
				return this.GetTable<Vouchers_Type>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Installmentubdate> Tb_Installmentubdates
		{
			get
			{
				return this.GetTable<Tb_Installmentubdate>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Installment> Tb_Installments
		{
			get
			{
				return this.GetTable<Tb_Installment>();
			}
		}
		
		public System.Data.Linq.Table<View_Installment> View_Installments
		{
			get
			{
				return this.GetTable<View_Installment>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_HrEmp")]
	public partial class Tb_HrEmp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EmpNo;
		
		private string _FullNameArab;
		
		private string _FullNameEng;
		
		private string _IqamaNo;
		
		private System.Nullable<bool> _Is_deleted;
		
		private EntitySet<Tb_Voucher> _Tb_Vouchers;
		
		private EntitySet<Tb_Voucher> _Tb_Vouchers1;
		
		private EntitySet<Tb_Voucher> _Tb_Vouchers2;
		
		private EntitySet<Tb_Voucher> _Tb_Vouchers3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnFullNameArabChanging(string value);
    partial void OnFullNameArabChanged();
    partial void OnFullNameEngChanging(string value);
    partial void OnFullNameEngChanged();
    partial void OnIqamaNoChanging(string value);
    partial void OnIqamaNoChanged();
    partial void OnIs_deletedChanging(System.Nullable<bool> value);
    partial void OnIs_deletedChanged();
    #endregion
		
		public Tb_HrEmp()
		{
			this._Tb_Vouchers = new EntitySet<Tb_Voucher>(new Action<Tb_Voucher>(this.attach_Tb_Vouchers), new Action<Tb_Voucher>(this.detach_Tb_Vouchers));
			this._Tb_Vouchers1 = new EntitySet<Tb_Voucher>(new Action<Tb_Voucher>(this.attach_Tb_Vouchers1), new Action<Tb_Voucher>(this.detach_Tb_Vouchers1));
			this._Tb_Vouchers2 = new EntitySet<Tb_Voucher>(new Action<Tb_Voucher>(this.attach_Tb_Vouchers2), new Action<Tb_Voucher>(this.detach_Tb_Vouchers2));
			this._Tb_Vouchers3 = new EntitySet<Tb_Voucher>(new Action<Tb_Voucher>(this.attach_Tb_Vouchers3), new Action<Tb_Voucher>(this.detach_Tb_Vouchers3));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameArab", DbType="NVarChar(200)")]
		public string FullNameArab
		{
			get
			{
				return this._FullNameArab;
			}
			set
			{
				if ((this._FullNameArab != value))
				{
					this.OnFullNameArabChanging(value);
					this.SendPropertyChanging();
					this._FullNameArab = value;
					this.SendPropertyChanged("FullNameArab");
					this.OnFullNameArabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameEng", DbType="NVarChar(200)")]
		public string FullNameEng
		{
			get
			{
				return this._FullNameEng;
			}
			set
			{
				if ((this._FullNameEng != value))
				{
					this.OnFullNameEngChanging(value);
					this.SendPropertyChanging();
					this._FullNameEng = value;
					this.SendPropertyChanged("FullNameEng");
					this.OnFullNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaNo", DbType="NVarChar(30)")]
		public string IqamaNo
		{
			get
			{
				return this._IqamaNo;
			}
			set
			{
				if ((this._IqamaNo != value))
				{
					this.OnIqamaNoChanging(value);
					this.SendPropertyChanging();
					this._IqamaNo = value;
					this.SendPropertyChanged("IqamaNo");
					this.OnIqamaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_deleted", DbType="Bit")]
		public System.Nullable<bool> Is_deleted
		{
			get
			{
				return this._Is_deleted;
			}
			set
			{
				if ((this._Is_deleted != value))
				{
					this.OnIs_deletedChanging(value);
					this.SendPropertyChanging();
					this._Is_deleted = value;
					this.SendPropertyChanged("Is_deleted");
					this.OnIs_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher", Storage="_Tb_Vouchers", ThisKey="EmpNo", OtherKey="Approved_By")]
		public EntitySet<Tb_Voucher> Tb_Vouchers
		{
			get
			{
				return this._Tb_Vouchers;
			}
			set
			{
				this._Tb_Vouchers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher1", Storage="_Tb_Vouchers1", ThisKey="EmpNo", OtherKey="Emp_Id")]
		public EntitySet<Tb_Voucher> Tb_Vouchers1
		{
			get
			{
				return this._Tb_Vouchers1;
			}
			set
			{
				this._Tb_Vouchers1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher2", Storage="_Tb_Vouchers2", ThisKey="EmpNo", OtherKey="Recived_By")]
		public EntitySet<Tb_Voucher> Tb_Vouchers2
		{
			get
			{
				return this._Tb_Vouchers2;
			}
			set
			{
				this._Tb_Vouchers2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher3", Storage="_Tb_Vouchers3", ThisKey="EmpNo", OtherKey="Requsted_By")]
		public EntitySet<Tb_Voucher> Tb_Vouchers3
		{
			get
			{
				return this._Tb_Vouchers3;
			}
			set
			{
				this._Tb_Vouchers3.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Vouchers(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.AprrovedBy = this;
		}
		
		private void detach_Tb_Vouchers(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.AprrovedBy = null;
		}
		
		private void attach_Tb_Vouchers1(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.EmployeeName = this;
		}
		
		private void detach_Tb_Vouchers1(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.EmployeeName = null;
		}
		
		private void attach_Tb_Vouchers2(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.RecivedBy = this;
		}
		
		private void detach_Tb_Vouchers2(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.RecivedBy = null;
		}
		
		private void attach_Tb_Vouchers3(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.RequstedBy = this;
		}
		
		private void detach_Tb_Vouchers3(Tb_Voucher entity)
		{
			this.SendPropertyChanging();
			entity.RequstedBy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Vouchers")]
	public partial class Tb_Voucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Serial;
		
		private string _Id;
		
		private string _Emp_Id;
		
		private string _Approved_By;
		
		private string _Requsted_By;
		
		private string _Recived_By;
		
		private string _Payment_Way;
		
		private string _Cheque_No;
		
		private string _Cheque_Bank;
		
		private System.Nullable<System.DateTime> _Cheque_Date;
		
		private System.Nullable<bool> _Is_Cheque;
		
		private System.Nullable<System.DateTime> _Requste_Date;
		
		private System.Nullable<System.DateTime> _Approved_Date;
		
		private System.Nullable<System.DateTime> _Recived_Date;
		
		private System.Nullable<bool> _deducted_from_salary;
		
		private string _Type;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<bool> _Is_Approved;
		
		private System.Nullable<bool> _Is_Receved;
		
		private System.Nullable<bool> _Is_deleted;
		
		private System.Nullable<bool> _is_Repayment;
		
		private EntitySet<Tb_Installment> _Tb_Installments;
		
		private EntityRef<Tb_HrEmp> _Tb_HrEmp;
		
		private EntityRef<Tb_HrEmp> _Tb_HrEmp1;
		
		private EntityRef<Tb_HrEmp> _Tb_HrEmp2;
		
		private EntityRef<Tb_HrEmp> _Tb_HrEmp3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSerialChanging(long value);
    partial void OnSerialChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnEmp_IdChanging(string value);
    partial void OnEmp_IdChanged();
    partial void OnApproved_ByChanging(string value);
    partial void OnApproved_ByChanged();
    partial void OnRequsted_ByChanging(string value);
    partial void OnRequsted_ByChanged();
    partial void OnRecived_ByChanging(string value);
    partial void OnRecived_ByChanged();
    partial void OnPayment_WayChanging(string value);
    partial void OnPayment_WayChanged();
    partial void OnCheque_NoChanging(string value);
    partial void OnCheque_NoChanged();
    partial void OnCheque_BankChanging(string value);
    partial void OnCheque_BankChanged();
    partial void OnCheque_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCheque_DateChanged();
    partial void OnIs_ChequeChanging(System.Nullable<bool> value);
    partial void OnIs_ChequeChanged();
    partial void OnRequste_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRequste_DateChanged();
    partial void OnApproved_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnApproved_DateChanged();
    partial void OnRecived_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRecived_DateChanged();
    partial void Ondeducted_from_salaryChanging(System.Nullable<bool> value);
    partial void Ondeducted_from_salaryChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnIs_ApprovedChanging(System.Nullable<bool> value);
    partial void OnIs_ApprovedChanged();
    partial void OnIs_RecevedChanging(System.Nullable<bool> value);
    partial void OnIs_RecevedChanged();
    partial void OnIs_deletedChanging(System.Nullable<bool> value);
    partial void OnIs_deletedChanged();
    partial void Onis_RepaymentChanging(System.Nullable<bool> value);
    partial void Onis_RepaymentChanged();
    #endregion
		
		public Tb_Voucher()
		{
			this._Tb_Installments = new EntitySet<Tb_Installment>(new Action<Tb_Installment>(this.attach_Tb_Installments), new Action<Tb_Installment>(this.detach_Tb_Installments));
			this._Tb_HrEmp = default(EntityRef<Tb_HrEmp>);
			this._Tb_HrEmp1 = default(EntityRef<Tb_HrEmp>);
			this._Tb_HrEmp2 = default(EntityRef<Tb_HrEmp>);
			this._Tb_HrEmp3 = default(EntityRef<Tb_HrEmp>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Serial
		{
			get
			{
				return this._Serial;
			}
			set
			{
				if ((this._Serial != value))
				{
					this.OnSerialChanging(value);
					this.SendPropertyChanging();
					this._Serial = value;
					this.SendPropertyChanged("Serial");
					this.OnSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Id", DbType="NVarChar(50)")]
		public string Emp_Id
		{
			get
			{
				return this._Emp_Id;
			}
			set
			{
				if ((this._Emp_Id != value))
				{
					if (this._Tb_HrEmp1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmp_IdChanging(value);
					this.SendPropertyChanging();
					this._Emp_Id = value;
					this.SendPropertyChanged("Emp_Id");
					this.OnEmp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approved_By", DbType="NVarChar(50)")]
		public string Approved_By
		{
			get
			{
				return this._Approved_By;
			}
			set
			{
				if ((this._Approved_By != value))
				{
					if (this._Tb_HrEmp.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnApproved_ByChanging(value);
					this.SendPropertyChanging();
					this._Approved_By = value;
					this.SendPropertyChanged("Approved_By");
					this.OnApproved_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requsted_By", DbType="NVarChar(50)")]
		public string Requsted_By
		{
			get
			{
				return this._Requsted_By;
			}
			set
			{
				if ((this._Requsted_By != value))
				{
					if (this._Tb_HrEmp3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRequsted_ByChanging(value);
					this.SendPropertyChanging();
					this._Requsted_By = value;
					this.SendPropertyChanged("Requsted_By");
					this.OnRequsted_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recived_By", DbType="NVarChar(50)")]
		public string Recived_By
		{
			get
			{
				return this._Recived_By;
			}
			set
			{
				if ((this._Recived_By != value))
				{
					if (this._Tb_HrEmp2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRecived_ByChanging(value);
					this.SendPropertyChanging();
					this._Recived_By = value;
					this.SendPropertyChanged("Recived_By");
					this.OnRecived_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Way", DbType="NVarChar(50)")]
		public string Payment_Way
		{
			get
			{
				return this._Payment_Way;
			}
			set
			{
				if ((this._Payment_Way != value))
				{
					this.OnPayment_WayChanging(value);
					this.SendPropertyChanging();
					this._Payment_Way = value;
					this.SendPropertyChanged("Payment_Way");
					this.OnPayment_WayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_No", DbType="NVarChar(50)")]
		public string Cheque_No
		{
			get
			{
				return this._Cheque_No;
			}
			set
			{
				if ((this._Cheque_No != value))
				{
					this.OnCheque_NoChanging(value);
					this.SendPropertyChanging();
					this._Cheque_No = value;
					this.SendPropertyChanged("Cheque_No");
					this.OnCheque_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_Bank", DbType="NVarChar(50)")]
		public string Cheque_Bank
		{
			get
			{
				return this._Cheque_Bank;
			}
			set
			{
				if ((this._Cheque_Bank != value))
				{
					this.OnCheque_BankChanging(value);
					this.SendPropertyChanging();
					this._Cheque_Bank = value;
					this.SendPropertyChanged("Cheque_Bank");
					this.OnCheque_BankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Cheque_Date
		{
			get
			{
				return this._Cheque_Date;
			}
			set
			{
				if ((this._Cheque_Date != value))
				{
					this.OnCheque_DateChanging(value);
					this.SendPropertyChanging();
					this._Cheque_Date = value;
					this.SendPropertyChanged("Cheque_Date");
					this.OnCheque_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Cheque", DbType="Bit")]
		public System.Nullable<bool> Is_Cheque
		{
			get
			{
				return this._Is_Cheque;
			}
			set
			{
				if ((this._Is_Cheque != value))
				{
					this.OnIs_ChequeChanging(value);
					this.SendPropertyChanging();
					this._Is_Cheque = value;
					this.SendPropertyChanged("Is_Cheque");
					this.OnIs_ChequeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requste_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Requste_Date
		{
			get
			{
				return this._Requste_Date;
			}
			set
			{
				if ((this._Requste_Date != value))
				{
					this.OnRequste_DateChanging(value);
					this.SendPropertyChanging();
					this._Requste_Date = value;
					this.SendPropertyChanged("Requste_Date");
					this.OnRequste_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approved_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Approved_Date
		{
			get
			{
				return this._Approved_Date;
			}
			set
			{
				if ((this._Approved_Date != value))
				{
					this.OnApproved_DateChanging(value);
					this.SendPropertyChanging();
					this._Approved_Date = value;
					this.SendPropertyChanged("Approved_Date");
					this.OnApproved_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recived_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Recived_Date
		{
			get
			{
				return this._Recived_Date;
			}
			set
			{
				if ((this._Recived_Date != value))
				{
					this.OnRecived_DateChanging(value);
					this.SendPropertyChanging();
					this._Recived_Date = value;
					this.SendPropertyChanged("Recived_Date");
					this.OnRecived_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deducted_from_salary", DbType="Bit")]
		public System.Nullable<bool> deducted_from_salary
		{
			get
			{
				return this._deducted_from_salary;
			}
			set
			{
				if ((this._deducted_from_salary != value))
				{
					this.Ondeducted_from_salaryChanging(value);
					this.SendPropertyChanging();
					this._deducted_from_salary = value;
					this.SendPropertyChanged("deducted_from_salary");
					this.Ondeducted_from_salaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Approved", DbType="Bit")]
		public System.Nullable<bool> Is_Approved
		{
			get
			{
				return this._Is_Approved;
			}
			set
			{
				if ((this._Is_Approved != value))
				{
					this.OnIs_ApprovedChanging(value);
					this.SendPropertyChanging();
					this._Is_Approved = value;
					this.SendPropertyChanged("Is_Approved");
					this.OnIs_ApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Receved", DbType="Bit")]
		public System.Nullable<bool> Is_Receved
		{
			get
			{
				return this._Is_Receved;
			}
			set
			{
				if ((this._Is_Receved != value))
				{
					this.OnIs_RecevedChanging(value);
					this.SendPropertyChanging();
					this._Is_Receved = value;
					this.SendPropertyChanged("Is_Receved");
					this.OnIs_RecevedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_deleted", DbType="Bit")]
		public System.Nullable<bool> Is_deleted
		{
			get
			{
				return this._Is_deleted;
			}
			set
			{
				if ((this._Is_deleted != value))
				{
					this.OnIs_deletedChanging(value);
					this.SendPropertyChanging();
					this._Is_deleted = value;
					this.SendPropertyChanged("Is_deleted");
					this.OnIs_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_Repayment", DbType="Bit")]
		public System.Nullable<bool> is_Repayment
		{
			get
			{
				return this._is_Repayment;
			}
			set
			{
				if ((this._is_Repayment != value))
				{
					this.Onis_RepaymentChanging(value);
					this.SendPropertyChanging();
					this._is_Repayment = value;
					this.SendPropertyChanged("is_Repayment");
					this.Onis_RepaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Voucher_Tb_Installment", Storage="_Tb_Installments", ThisKey="Serial", OtherKey="v_id")]
		public EntitySet<Tb_Installment> Tb_Installments
		{
			get
			{
				return this._Tb_Installments;
			}
			set
			{
				this._Tb_Installments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher", Storage="_Tb_HrEmp", ThisKey="Approved_By", OtherKey="EmpNo", IsForeignKey=true)]
		public Tb_HrEmp AprrovedBy
		{
			get
			{
				return this._Tb_HrEmp.Entity;
			}
			set
			{
				Tb_HrEmp previousValue = this._Tb_HrEmp.Entity;
				if (((previousValue != value) 
							|| (this._Tb_HrEmp.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_HrEmp.Entity = null;
						previousValue.Tb_Vouchers.Remove(this);
					}
					this._Tb_HrEmp.Entity = value;
					if ((value != null))
					{
						value.Tb_Vouchers.Add(this);
						this._Approved_By = value.EmpNo;
					}
					else
					{
						this._Approved_By = default(string);
					}
					this.SendPropertyChanged("AprrovedBy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher1", Storage="_Tb_HrEmp1", ThisKey="Emp_Id", OtherKey="EmpNo", IsForeignKey=true)]
		public Tb_HrEmp EmployeeName
		{
			get
			{
				return this._Tb_HrEmp1.Entity;
			}
			set
			{
				Tb_HrEmp previousValue = this._Tb_HrEmp1.Entity;
				if (((previousValue != value) 
							|| (this._Tb_HrEmp1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_HrEmp1.Entity = null;
						previousValue.Tb_Vouchers1.Remove(this);
					}
					this._Tb_HrEmp1.Entity = value;
					if ((value != null))
					{
						value.Tb_Vouchers1.Add(this);
						this._Emp_Id = value.EmpNo;
					}
					else
					{
						this._Emp_Id = default(string);
					}
					this.SendPropertyChanged("EmployeeName");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher2", Storage="_Tb_HrEmp2", ThisKey="Recived_By", OtherKey="EmpNo", IsForeignKey=true)]
		public Tb_HrEmp RecivedBy
		{
			get
			{
				return this._Tb_HrEmp2.Entity;
			}
			set
			{
				Tb_HrEmp previousValue = this._Tb_HrEmp2.Entity;
				if (((previousValue != value) 
							|| (this._Tb_HrEmp2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_HrEmp2.Entity = null;
						previousValue.Tb_Vouchers2.Remove(this);
					}
					this._Tb_HrEmp2.Entity = value;
					if ((value != null))
					{
						value.Tb_Vouchers2.Add(this);
						this._Recived_By = value.EmpNo;
					}
					else
					{
						this._Recived_By = default(string);
					}
					this.SendPropertyChanged("RecivedBy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_HrEmp_Tb_Voucher3", Storage="_Tb_HrEmp3", ThisKey="Requsted_By", OtherKey="EmpNo", IsForeignKey=true)]
		public Tb_HrEmp RequstedBy
		{
			get
			{
				return this._Tb_HrEmp3.Entity;
			}
			set
			{
				Tb_HrEmp previousValue = this._Tb_HrEmp3.Entity;
				if (((previousValue != value) 
							|| (this._Tb_HrEmp3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_HrEmp3.Entity = null;
						previousValue.Tb_Vouchers3.Remove(this);
					}
					this._Tb_HrEmp3.Entity = value;
					if ((value != null))
					{
						value.Tb_Vouchers3.Add(this);
						this._Requsted_By = value.EmpNo;
					}
					else
					{
						this._Requsted_By = default(string);
					}
					this.SendPropertyChanged("RequstedBy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Installments(Tb_Installment entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Voucher = this;
		}
		
		private void detach_Tb_Installments(Tb_Installment entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Voucher = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vouchers_Types")]
	public partial class Vouchers_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Type;
		
		private System.Nullable<bool> _deducted_from_salary;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void Ondeducted_from_salaryChanging(System.Nullable<bool> value);
    partial void Ondeducted_from_salaryChanged();
    #endregion
		
		public Vouchers_Type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deducted_from_salary", DbType="Bit")]
		public System.Nullable<bool> deducted_from_salary
		{
			get
			{
				return this._deducted_from_salary;
			}
			set
			{
				if ((this._deducted_from_salary != value))
				{
					this.Ondeducted_from_salaryChanging(value);
					this.SendPropertyChanging();
					this._deducted_from_salary = value;
					this.SendPropertyChanged("deducted_from_salary");
					this.Ondeducted_from_salaryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Installments")]
	public partial class Tb_Installmentubdate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<System.DateTime> _Repayment_Date;
		
		private System.Nullable<bool> _is_Repayment;
		
		private System.Nullable<bool> _Canceled;
		
		private System.Nullable<bool> _is_deleted;
		
		private System.Nullable<decimal> _Amount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnRepayment_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRepayment_DateChanged();
    partial void Onis_RepaymentChanging(System.Nullable<bool> value);
    partial void Onis_RepaymentChanged();
    partial void OnCanceledChanging(System.Nullable<bool> value);
    partial void OnCanceledChanged();
    partial void Onis_deletedChanging(System.Nullable<bool> value);
    partial void Onis_deletedChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    #endregion
		
		public Tb_Installmentubdate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Repayment_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Repayment_Date
		{
			get
			{
				return this._Repayment_Date;
			}
			set
			{
				if ((this._Repayment_Date != value))
				{
					this.OnRepayment_DateChanging(value);
					this.SendPropertyChanging();
					this._Repayment_Date = value;
					this.SendPropertyChanged("Repayment_Date");
					this.OnRepayment_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_Repayment", DbType="Bit")]
		public System.Nullable<bool> is_Repayment
		{
			get
			{
				return this._is_Repayment;
			}
			set
			{
				if ((this._is_Repayment != value))
				{
					this.Onis_RepaymentChanging(value);
					this.SendPropertyChanging();
					this._is_Repayment = value;
					this.SendPropertyChanged("is_Repayment");
					this.Onis_RepaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canceled", DbType="Bit")]
		public System.Nullable<bool> Canceled
		{
			get
			{
				return this._Canceled;
			}
			set
			{
				if ((this._Canceled != value))
				{
					this.OnCanceledChanging(value);
					this.SendPropertyChanging();
					this._Canceled = value;
					this.SendPropertyChanged("Canceled");
					this.OnCanceledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit")]
		public System.Nullable<bool> is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Installments")]
	public partial class Tb_Installment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<long> _v_id;
		
		private System.Nullable<System.DateTime> _Repayment_Date;
		
		private System.Nullable<bool> _is_Repayment;
		
		private System.Nullable<bool> _Canceled;
		
		private System.Nullable<bool> _is_deleted;
		
		private System.Nullable<decimal> _Amount;
		
		private EntityRef<Tb_Voucher> _Tb_Voucher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onv_idChanging(System.Nullable<long> value);
    partial void Onv_idChanged();
    partial void OnRepayment_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRepayment_DateChanged();
    partial void Onis_RepaymentChanging(System.Nullable<bool> value);
    partial void Onis_RepaymentChanged();
    partial void OnCanceledChanging(System.Nullable<bool> value);
    partial void OnCanceledChanged();
    partial void Onis_deletedChanging(System.Nullable<bool> value);
    partial void Onis_deletedChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    #endregion
		
		public Tb_Installment()
		{
			this._Tb_Voucher = default(EntityRef<Tb_Voucher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_v_id", DbType="BigInt")]
		public System.Nullable<long> v_id
		{
			get
			{
				return this._v_id;
			}
			set
			{
				if ((this._v_id != value))
				{
					if (this._Tb_Voucher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onv_idChanging(value);
					this.SendPropertyChanging();
					this._v_id = value;
					this.SendPropertyChanged("v_id");
					this.Onv_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Repayment_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Repayment_Date
		{
			get
			{
				return this._Repayment_Date;
			}
			set
			{
				if ((this._Repayment_Date != value))
				{
					this.OnRepayment_DateChanging(value);
					this.SendPropertyChanging();
					this._Repayment_Date = value;
					this.SendPropertyChanged("Repayment_Date");
					this.OnRepayment_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_Repayment", DbType="Bit")]
		public System.Nullable<bool> is_Repayment
		{
			get
			{
				return this._is_Repayment;
			}
			set
			{
				if ((this._is_Repayment != value))
				{
					this.Onis_RepaymentChanging(value);
					this.SendPropertyChanging();
					this._is_Repayment = value;
					this.SendPropertyChanged("is_Repayment");
					this.Onis_RepaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canceled", DbType="Bit")]
		public System.Nullable<bool> Canceled
		{
			get
			{
				return this._Canceled;
			}
			set
			{
				if ((this._Canceled != value))
				{
					this.OnCanceledChanging(value);
					this.SendPropertyChanging();
					this._Canceled = value;
					this.SendPropertyChanged("Canceled");
					this.OnCanceledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit")]
		public System.Nullable<bool> is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Voucher_Tb_Installment", Storage="_Tb_Voucher", ThisKey="v_id", OtherKey="Serial", IsForeignKey=true)]
		public Tb_Voucher Tb_Voucher
		{
			get
			{
				return this._Tb_Voucher.Entity;
			}
			set
			{
				Tb_Voucher previousValue = this._Tb_Voucher.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Voucher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Voucher.Entity = null;
						previousValue.Tb_Installments.Remove(this);
					}
					this._Tb_Voucher.Entity = value;
					if ((value != null))
					{
						value.Tb_Installments.Add(this);
						this._v_id = value.Serial;
					}
					else
					{
						this._v_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("Tb_Voucher");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Installment")]
	public partial class View_Installment
	{
		
		private string _FullNameArab;
		
		private long _id;
		
		private System.Nullable<long> _v_id;
		
		private System.Nullable<System.DateTime> _Repayment_Date;
		
		private System.Nullable<bool> _is_Repayment;
		
		private string _FullNameEng;
		
		private string _IqamaNo;
		
		private string _EmpNo;
		
		private long _Serial;
		
		private string _Payment_Way;
		
		private string _Cheque_No;
		
		private string _Cheque_Bank;
		
		private System.Nullable<System.DateTime> _Cheque_Date;
		
		private System.Nullable<System.DateTime> _Requste_Date;
		
		private string _Type;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<decimal> _installment_Amount;
		
		public View_Installment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameArab", DbType="NVarChar(200)")]
		public string FullNameArab
		{
			get
			{
				return this._FullNameArab;
			}
			set
			{
				if ((this._FullNameArab != value))
				{
					this._FullNameArab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL")]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_v_id", DbType="BigInt")]
		public System.Nullable<long> v_id
		{
			get
			{
				return this._v_id;
			}
			set
			{
				if ((this._v_id != value))
				{
					this._v_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Repayment_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Repayment_Date
		{
			get
			{
				return this._Repayment_Date;
			}
			set
			{
				if ((this._Repayment_Date != value))
				{
					this._Repayment_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_Repayment", DbType="Bit")]
		public System.Nullable<bool> is_Repayment
		{
			get
			{
				return this._is_Repayment;
			}
			set
			{
				if ((this._is_Repayment != value))
				{
					this._is_Repayment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameEng", DbType="NVarChar(200)")]
		public string FullNameEng
		{
			get
			{
				return this._FullNameEng;
			}
			set
			{
				if ((this._FullNameEng != value))
				{
					this._FullNameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IqamaNo", DbType="NVarChar(30)")]
		public string IqamaNo
		{
			get
			{
				return this._IqamaNo;
			}
			set
			{
				if ((this._IqamaNo != value))
				{
					this._IqamaNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this._EmpNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial", DbType="BigInt NOT NULL")]
		public long Serial
		{
			get
			{
				return this._Serial;
			}
			set
			{
				if ((this._Serial != value))
				{
					this._Serial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Way", DbType="NVarChar(50)")]
		public string Payment_Way
		{
			get
			{
				return this._Payment_Way;
			}
			set
			{
				if ((this._Payment_Way != value))
				{
					this._Payment_Way = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_No", DbType="NVarChar(50)")]
		public string Cheque_No
		{
			get
			{
				return this._Cheque_No;
			}
			set
			{
				if ((this._Cheque_No != value))
				{
					this._Cheque_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_Bank", DbType="NVarChar(50)")]
		public string Cheque_Bank
		{
			get
			{
				return this._Cheque_Bank;
			}
			set
			{
				if ((this._Cheque_Bank != value))
				{
					this._Cheque_Bank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheque_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Cheque_Date
		{
			get
			{
				return this._Cheque_Date;
			}
			set
			{
				if ((this._Cheque_Date != value))
				{
					this._Cheque_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requste_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Requste_Date
		{
			get
			{
				return this._Requste_Date;
			}
			set
			{
				if ((this._Requste_Date != value))
				{
					this._Requste_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_installment_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> installment_Amount
		{
			get
			{
				return this._installment_Amount;
			}
			set
			{
				if ((this._installment_Amount != value))
				{
					this._installment_Amount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
